### ISSUE TITLE
Access Token problem

### ISSUE THREAD

**Issue by dihiaselma** [strohne/Facepager#102]

**Comment by dihiaselma** [comment]
Hi;
I've installed the Facepager 3.10 , but when I try to connect to facebook in order to get an access token it still empty.   despite, I get sucess but the acess token field is empty.
Knowing that I've chnaged the api version in Facepager\DefaultPresets files into 3.2 rather than 2.12.

Please what should I do?

**Comment by strohne** [comment]
Hi, any error messages in the status view?

**Comment by dihiaselma** [comment]
no error . it write Sucess. but no access token

I tried all the version 
even 4.0(it generated the access tken, but no page post, no page comments in the ressources tab.)

**Comment by strohne** [comment]
Strange. But if v4.0 works go with it. 

Entries in the resource field are only hints, not needed, they are even outdated. We are working on updating this. Use the presets, they should be fine.

There were/are some bugs in the latest release. I updated the installer a minute ago, please download again.

**Comment by dihiaselma** [comment]
OK, i'll try it and inform you. Thank you

**Comment by dihiaselma** [comment]
This version is working . thank you

**Comment by Talha1721** [comment]
Hello, i am new to facepager. I want to collect allowed individual's facebook posts for my thesis purpose. I have followed all the steps as described. But when try to log in facebook, it shows success but don't provide access token.
NB: I am using the (Facepager_Setup_4_2_22.windows.exe ) latest version
       I have tried graph.facebook.com/v3.2 (default)  and graph.facebook.com/v8.0[change from this file 
       Facebook.oa3.json  all v3.2 to v8.0 ]
       My OS windows10 updated version, not genuine
![Facepager](https://user-images.githubusercontent.com/69380371/89704463-bb992b80-d975-11ea-8576-8d1374180f72.JPG)
