### ISSUE TITLE
Twitter's tweet_mode='extended' parameter doesn't give full text

### ISSUE THREAD

**Issue by dhsdshdhk** [strohne/Facepager#104]
I fetched some data using tweet_mode extended and noticed two problems.
1. The full_text column does not show the full text for RTs, only normal tweets.
2. After the first offcut, full_text is empty for all entries and they're all in the text column.

Screenshot:

![Capturar1](https://user-images.githubusercontent.com/28062763/58491462-617fc200-8145-11e9-86e9-dcb073d263fc.PNG)

Running on Windows 10, latest version.

**Comment by strohne** [comment]
thanks for your feedback. can you provide more details about the query settings?
and did you check what kind of data is in the detail view?

**Comment by strohne** [comment]
I got it. Looks like a paging bug in the Twitter API. I created a workaround, the build will be provided as soon as possible.

btw: in extended mode you should adjust the column settings, `full_text` replaces `text`, see https://developer.twitter.com/en/docs/tweets/tweet-updates.html

**Comment by dhsdshdhk** [comment]
>in extended mode you should adjust the column settings, full_text replaces text
Yes. As you see in the screenshot I first activated `full_text`, then it wasn't showing anything after the cutoff, so I activated `text` as well and found out the values were there, instead of where they should have been.

**Comment by strohne** [comment]
I updated the latest release. Thanks again for opening the issue!
