### ISSUE TITLE
Twitter Streaming won't fetch for more than one node simultaneously

### ISSUE THREAD

**Issue by dhsdshdhk** [strohne/Facepager#105]
When selecting two nodes, it only fetches data for the first one (the first which was selected, I think) and leaves 1 node remaining forever, which is never fetched. Tested on Windows 10 latest version.
EDIT: also important to say, I tried changing parallel threads to 2 thinking it would solve the problem, but nothing changed. It still ran with only 1 active thread, fetching for only one node.

**Comment by strohne** [comment]
This is true. Never thought about it. You need it?

**Comment by dhsdshdhk** [comment]
It would be a nice addition if it's not too complicated.

**Comment by strohne** [comment]
Now we can. Increase the threads, each thread catches one node.
