### ISSUE TITLE
"Data could not be converted to JSON" error getting data from facebook

### ISSUE THREAD

**Issue by rumjhum-dorin** [strohne/Facepager#107]
"Data could not be converted to JSON"  couldnot fetch facebook data..how to resolve?

**Comment by strohne** [comment]
please be more precise, how can I reproduce the issue?

**Comment by rumjhum-dorin** [comment]
I have just installed facepager and was trying to collect data from
facebook as test basis.. but getting that error.. can u suggest me
authentic tutorial of face pager and if there is any prerequisite s/w for
this?


*Farkhunda Dorin*
Senior Management Counsellor
Bangladesh Institute of Management,
Ministry of Industries, Govt. of the People's Republic of Bangladesh

Master Trainer ,Innovation Team, A2i, ICT Division
Master Trainer ,SPS Team, A2i, ICT Division

M : +8801711907418,+8801610005155
e : farkhunda.dorin@bim.gov.bd

**Comment by strohne** [comment]
you opened a ticket in the development issue system. I can not reproduce the issue without details. Please see the Wiki and ask questions about how to use Facepager in the Facebook user group. All this is linked on the project page. sorry, I close the issue here.
