### ISSUE TITLE
Timer seems to be broken

### ISSUE THREAD

**Issue by dhsdshdhk** [strohne/Facepager#108]
When using the timer, it will only search the first time. The second time, a message saying 0 nodes selected appears and it doesn't search anything. Had to do a bash script with xdotool to click Fetch Data every 20 minutes.

**Comment by strohne** [comment]
Thanks for posting the issue, I will look into it. Some of the recent changes may have broken the timer function.

**Comment by strohne** [comment]
I fixed the issue and updated the releases. @dhsdshdhk Thanks for pointing this out.
