### ISSUE TITLE
Access Token Missing

### ISSUE THREAD

**Issue by rheemarc15** [strohne/Facepager#110]
Can anyone help me , I just need it for my Thesis can't fetch the data and always need to log in even I have a developers account for facebook
![Error](https://user-images.githubusercontent.com/55224655/64754642-c4f9f800-d55a-11e9-8edd-ebbc8d98d551.JPG)
![Status](https://user-images.githubusercontent.com/55224655/64754643-c4f9f800-d55a-11e9-9e90-0d60e34009f3.JPG)

**Comment by rheemarc15** [comment]
My token is fine right now , now I'm having another issue sorry but I'm just new in here facepager and facebook developers and I'm having problem in fetching the data.
The error says "(#10) To use ‘Page Public Content Access’, your use of this endpoint must be rev"
![another one](https://user-images.githubusercontent.com/55224655/65400721-81bf4500-ddf6-11e9-8779-2af97b4493d5.JPG)
![another two](https://user-images.githubusercontent.com/55224655/65400733-8552cc00-ddf6-11e9-9693-d29d946ed97b.JPG)

**Comment by strohne** [comment]
This is due to Facebook shuttung down access to the API, see the discussion in the Facebook group. This is no development issue, I close the issue. Have fun with other APIs :)

**Comment by victornobre1996** [comment]
hi, i need your help! 
![image](https://user-images.githubusercontent.com/65187343/86064724-32243e80-ba44-11ea-9c8b-4104a569fa4d.png)

this erros is appear for me

**Comment by victornobre1996** [comment]
access token not appear for me. How can i  resolve this problem?

**Comment by strohne** [comment]
@victornobre1996 Please don't hijack threads. As we wrote in the Facebook group, this is a driver problem of you Microsoft Surface. Looks like it is not compatible with the webbrowser included in Qt for Python (PySide2).  I will delete the messages here, but if you want open up a new issue. Unfortunately, we don't have a solution other than switching the device, try another computer. If you know someone who can dig into the problem, let me know.
