### ISSUE TITLE
Failed to create openGL context

### ISSUE THREAD

**Issue by meriem-k** [strohne/Facepager#112]
Hello, I installed facpager 4.0 once I login facebook or google it outputs an error msg: Faild create opengl 2.0 .
of solutions

**Comment by meriem-k** [comment]
bonjour, j'ai installer facpager 4.0 une fois je fait login facebook ou google il sort un msg d'erreur : Faild create opengl 2.0 .
des solutions

**Comment by strohne** [comment]
Hi, can you be more precise about the error message, is it "Failed to create openGL context"? Might be an issue with outdated graphics card drivers. See https://www.drivereasy.com/knowledge/fixed-failed-to-create-opengl-context-for-format-qsurfaceformat/

**Comment by strohne** [comment]
I close the issue due to missing information.
