### ISSUE TITLE
4.1.6: Failed to execute script facepager

### ISSUE THREAD

**Issue by sadoMasupilami** [strohne/Facepager#115]
Hello,

i tried the newest version on two different WIN10 Computers always with this error message.
The older version 4.0.10 works fine.

Thank you for that great peace of software!

**Comment by strohne** [comment]
Thanks for the report. This is an issue related to bundling the release (cchardet is not imported). I will fix it soon,

**Comment by strohne** [comment]
May I ask you to try the latest version (4.1.7)? Hopefully fixed. 

https://github.com/strohne/Facepager/releases

**Comment by sadoMasupilami** [comment]
hello,
sorry for not responding but i was on holiday.
Thank you for fixing the problem!
