### ISSUE TITLE
Unable to fetch facebook comments due to some error

### ISSUE THREAD

**Issue by rheemarc15** [strohne/Facepager#116]
I cant gather my data for my research paper , and the pages I need to gather are Tele-Companies in our country but I've try many times still error of Page Public Content something. I am using Facepager 3.5
![Capture](https://user-images.githubusercontent.com/55224655/73899798-a78e4780-48c8-11ea-8b64-db7d3b9b10e3.JPG)

**Comment by strohne** [comment]
Hi. Did you try the latest version? V3.5 is outdated. Furthermore, access to Facebook is restricted by Facebook. Depends on the API version and may be further restricted in the future.

Am 6. Februar 2020 03:09:04 MEZ schrieb rheemarc15 <notifications@github.com>:
