### ISSUE TITLE
ImportError when trying to run Facepager on Ubuntu 18.04

### ISSUE THREAD

**Issue by McCastles** [strohne/Facepager#119]
Hello, thank you for the effort in developing Facepager!

I'm following the installation instruction [here](https://github.com/strohne/Facepager/blob/master/src/readme.md) and as I try to run ```python3 Facepager.py``` the following appears:

```
Traceback (most recent call last):
  File "Facepager.py", line 38, in <module>
    from actions import *
  File "/home/stud/Facepager/src/actions.py", line 9, in <module>
    from apimodules import *
  File "/home/stud/Facepager/src/apimodules.py", line 14, in <module>
    from PySide2.QtWebEngineWidgets import QWebEngineView, QWebEnginePage, QWebEngineProfile
ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
```
I've read the similar issue thread [here](https://github.com/strohne/Facepager/issues/99) but haven't find the solution.

I tried:

- Double-checking the environment and package versions (PySide2 version is 5.11.1)
- Updating PySide2 to the newest version (didn't work)
- Importing PySide2 and run ```help``` on it, to see that QtWebEngineWidgets is present, but cannot by any means be imported itself.

I'm extremely sorry if this issue has already been solved, I hope I've just missed something obviously dumb. Thank you.

**Comment by strohne** [comment]
I did some research on the issue but, at the moment, I can only admit: no idea. Could this be a driver issue? See for example https://github.com/spyder-ide/spyder/issues/7371 Does installing pyopengl help?

**Comment by strohne** [comment]
I tested it in a virtual machine with Ubuntu 18.04.01 LTS, works without problems. *confused*. You activated the environment (`source pyenv/bin/activate`) and installed the packages inside the environment and started Facepager from the environment, right?

And do you have tge missing file libEGL.so on your machine? That's what it looks like in my virtual box:

![grafik](https://user-images.githubusercontent.com/1856212/77120429-2387bd80-6a39-11ea-876e-9e2694e97955.png)

**Comment by McCastles** [comment]
Thank you very much for the answer.

libEGL is evidently missing on my system:
![image](https://user-images.githubusercontent.com/37660564/77157051-aba9a980-6ab1-11ea-9368-a43284e972fd.png)

Just to be sure I've just deleted the whole thing and done it step by step from the beginning. I do activate the environment and install packages inside. Installing `pyopengl` didn't help.

The only possible (possibly misleading) clue I've got is this: when I install the packages, some of them seem to produce a failure message:
![image](https://user-images.githubusercontent.com/37660564/77157577-b31d8280-6ab2-11ea-8f44-8e0035c1a794.png)

Though the output says both `rauth` and `SQLAlchemy` are installed successfully: https://pastebin.com/raw/ZQWYVZtq

If you learn something about the possible solution, please let me know, thank you once again.

**Comment by strohne** [comment]
It doesn't look like the packages are correctly installed. Maybe wheel is missing? Googling the error message brings up: https://stackoverflow.com/a/59596814/2746414

```
sudo apt-get install gcc libpq-dev -y
sudo apt-get install python-dev  python-pip -y
sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
pip3 install wheel
```

**Comment by McCastles** [comment]
@strohne I'm sorry I screwed up a little bit, I was late to realize that the remote machine I'm working on lacks the graphical interface (gnome) so my logic of installing Facepager there was flawed. 

Is there any change Facepager can be installed and run in a command-line mode? That would have resolved my problem.

Sorry for confusion.

**Comment by strohne** [comment]
Very funny, you made my day :)

At the moment, there is no command line option, sorry. But this is a much requested feature and I have been thinking about this for some time now. If you or someone else has lots of time, I would try to guide through refactoring the code. But it would be more efficient for you to compile your own scripts, I guess.
