### ISSUE TITLE
Lizensierung

### ISSUE THREAD

**Issue by dorvak** [strohne/Facepager#12]
Damit irgendwelche Unternehmen nicht einfach den Code kopieren, sollten wir mal über eine Lizent a´la GNU/GPL oder MIT nachdenken.

**Comment by strohne** [comment]
Wollen wir bei Gelegenheit mal MIT-Lizenz dranschreiben?

**Comment by dorvak** [comment]
Ja, lass einfach die MIT-Lizenz nehmen, die Copyleft-Sache und die proprietäre bzw. kommerzielle Nutzung ist mir eigtl. auch recht egal ^^

**Comment by strohne** [comment]
Habe ich in der readme und in der Facepager.py ergänzt,. Gelegentlich könnte man alle Dateien noch einzeln mit den entsprechenden Daten versehen, vorerst dürfte das aber ausreichen,
