### ISSUE TITLE
Bug when querying Facebook engagement data for an URL

### ISSUE THREAD

**Issue by alexgonca** [strohne/Facepager#120]
I think the latest release introduced a bug when querying Facebook engagement data for an URL.
Two nodes are being created under the seed node: an empty node and an offcut node.
Oddly, the engagement data is actually inside the offcut node.

Before the latest release, only a data node was created and it contained the engagement data.

I am attaching a screenshot so you can see what I mean:
![Annotation 2020-03-23 135208](https://user-images.githubusercontent.com/3498008/77347073-aa74b880-6d0d-11ea-9175-60e8cb046e9e.png)

And this is the "right" behavior (version 4.1.7):
![right one](https://user-images.githubusercontent.com/3498008/77348194-697da380-6d0f-11ea-8d03-4a79fdc5eaca.png)

I am running Facepager on Windows 10
Thanks a million (as always)!

**Comment by strohne** [comment]
Well, that's a side effect of streamlining the code and OpenAPI integration. I need to think about how to best fix it without introducing new bugs.  Thank you for opening the issue!

**Comment by strohne** [comment]
I think I found a proper solution, will be included in the next release. (My goal is to move these kinds of settings into OpenAPI files, still on the way.)

**Comment by strohne** [comment]
Fixed & released. Looking forward to new bugs :)
