### ISSUE TITLE
Minor suggestion: add a slash before <Object ID> in the Resource field

### ISSUE THREAD

**Issue by alexgonca** [strohne/Facepager#121]
All the pre-filled resources have slash before them, except <Object ID>:

![backlash](https://user-images.githubusercontent.com/3498008/77348552-093b3180-6d10-11ea-8c31-a45f14ce3099.png)

I think it is good to add it there too.
Otherwise, the user will have to add it anyway (because there is no slash at the end of the Base path).

Thank you!

**Comment by strohne** [comment]
Thanks for the hint. This is leftover from earlier refactoring. I changed it in the code, will be in the next release (coming soon).

**Comment by strohne** [comment]
Fixed & released. Looking forward to new bugs :)

After updating, default API definitions need to be reloaded. Start Facepager, wait for the message in the status log, restart Facepager.
