### ISSUE TITLE
Error when opening Facepager 

### ISSUE THREAD

**Issue by YazidKurdi** [strohne/Facepager#124]
I was working on Facepager, I closed and reopened the app and attached you can find the error that followed.

![error](https://user-images.githubusercontent.com/50083367/79080565-b35e1600-7d1e-11ea-9ecb-cfc00eefbd3c.PNG)

**Comment by strohne** [comment]
Thanks for the bug report. Is this a permanent error? One cause could be an unstable connection to GitHub. When the API definitions are not completley downloaded such errors might occur.
