### ISSUE TITLE
fields (from) doesn't work in comments

### ISSUE THREAD

**Issue by hshehari** [strohne/Facepager#125]
I'm trying to fetch comments from a Facebook post,
I entered these fields (id, from, attachment, created_time, message, like_count)
The results contain all information except (from)

![issue](https://user-images.githubusercontent.com/4148800/80839653-40b1cd80-8c2e-11ea-992e-fbd5b765548d.jpg)

**Comment by strohne** [comment]
Hi. This is no Facepager issue. Facebook restricts access to user information. See the API reference of Facebook.
