### ISSUE TITLE
Get data from a group

### ISSUE THREAD

**Issue by abomokhahmed** [strohne/Facepager#126]
Hii
Can facepager fetch data from groups?
I tried it on pages and it worked just fine.
But when I tried it on a group it didn't work.
The group that **didn't work**:
AlRaqeemQuranMiracles
Nnd it's facebook url is:
https://www.facebook.com/groups/AlRaqeemQuranMiracles/

Example of a page that **worked**:
https://www.facebook.com/Behind.Numbersss/

Have any idea why is that and what should I do?
I am a member of both of them.

**Comment by strohne** [comment]
Facebook restricts access to groups. I close the issue since this is not related to development. Please ask questions about using Facebook in the Facebook user group (you find the link in the wiki).
