### ISSUE TITLE
Scraping Youtube Video Tags

### ISSUE THREAD

**Issue by weebkai** [strohne/Facepager#127]
I tried to scrape video tags from youtube. Therefore, I used the resource "/videos" and the scope "https://www.googleapis.com/auth/youtube.force-ssl". FacePager gives me every other snippet-information except of video tags. What can I do to make this run?

**Comment by strohne** [comment]
Can you please ask this question in the Facebook User Group and provide an example? This is not a development issue, rather about using the YouTube API. Very interesting question, I will be happy to try this out and answer in the group.
