### ISSUE TITLE
'Shiboken.ObjectType' object is not iterable

### ISSUE THREAD

**Issue by shaneserrano** [strohne/Facepager#128]
Hello guys. I'm trying to install the Facepager in my Ubuntu OS but when I try to run it this error shows:

```
(pyenv) gigi@gigi-Lenovo-G50-80:~/Facepager/src$ python3 Facepager.py
Traceback (most recent call last):
  File "Facepager.py", line 36, in <module>
    from datatree import *
  File "/home/gigi/Facepager/src/datatree.py", line 322, in <module>
    class TreeModel(QAbstractItemModel):
TypeError: 'Shiboken.ObjectType' object is not iterable
```

I hope someone can help me :)

**Comment by strohne** [comment]
Thanks for the bug report! Looks like a compability issue, you use Python 3.8? See https://bugreports.qt.io/browse/PYSIDE-1140

Can you either switch to Python 3.7 or try a newer version of PySide? I think on Ubuntu the latest PySide might work, but I didn't try myself yet: `pip install PySide`

**Comment by shaneserrano** [comment]
Thanks strohne! 
I have downgraded to Python 3.7 however, I've encountered a new error.

`Traceback (most recent call last):
  File "Facepager.py", line 31, in <module>
    from PySide2.QtCore import *
ModuleNotFoundError: No module named 'PySide2'`

I have properly installed PySide2.

**Comment by strohne** [comment]
After downgrading, did you install all the packages using pip3?  Any errors related to PySide?

https://github.com/strohne/Facepager/blob/master/src/readme.md#steps-to-runder-under-ubuntu-18041-lts

**Comment by strohne** [comment]
> `pip install PySide`

Should be `pip3 install PySide2==5.11.1` or `pip3 install PySide2`

**Comment by shaneserrano** [comment]
Yeah. PySide2 has been installed properly. 
```
gigi@gigi-Lenovo-G50-80:~/Facepager$ pip3 install PySide2
Requirement already satisfied: PySide2 in ./pyenv/lib/python3.8/site-packages (5.11.1)
```

When installing the PySide, both pip and pip3 returns this error message:
```
gigi@gigi-Lenovo-G50-80:~/Facepager$ pip install PySide
Collecting PySide
  Using cached PySide-1.2.4.tar.gz (9.3 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/gigi/Facepager/pyenv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jrpni4k4/PySide/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jrpni4k4/PySide/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-jrpni4k4/PySide/pip-egg-info
         cwd: /tmp/pip-install-jrpni4k4/PySide/
    Complete output (1 lines):
    only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

I followed the guideline in readme.md properly

**Comment by strohne** [comment]
Sorry, I have no clue, looks fine. Can you post the whole session from the terminal here? Everything beginning with the step ` source pyenv/bin/activate` until `python3 Facepager.py`?

**Comment by strohne** [comment]
An could you execute the following commands in the terminal, from inside the Facepager folder?

```
source pyenv/bin/activate
python
import PySide2
quit()
```

**Comment by shaneserrano** [comment]
Hello strohne! My problem has been fixed!

What I did is created a new venv and forced the python3.7 to it when creating it.

Thank you so much! You've been a big help to me. :)

**Comment by strohne** [comment]
Great, have fun!
