### ISSUE TITLE
error_subcode 33

### ISSUE THREAD

**Issue by xyberscript** [strohne/Facepager#129]
I am scraping all comments of the videos from a certain page but a when I tried to scrape a specific video it throws an error. The other videos on the page was scraped successfully.

Video Link: https://www.facebook.com/519163941601957/videos/620427315348697/
/<post-id>/comments Object ID: 519163941601957_620427315348697

**Comment by strohne** [comment]
Hi. Thanks for the report. This is not a development issue, rather about using the Facebook API. I close the issue. Please ask such kind of questions in the Facepager user group on Facebook.

Regarding the problem: getting comments for live videos is not supported by the standard Graph API. There is a dedicated API for live videos, but I didn't try this and Facepager doesn't have access out of the box. You would need to register an own app and go through app review.
Best
