### ISSUE TITLE
Can't fetch data from Facebook

### ISSUE THREAD

**Issue by paulaG11** [strohne/Facepager#130]
Hi I keep getting this error:

2020-05-25 14:58:42.415922 Error 'error (400)' for 251857968167873 with message Unknown path components: /251857968167873/posts.

please help

Many thanks

Paula

**Comment by strohne** [comment]
Hi, this looks like an error from the Facebook API or from using Facepager with the wrong settings, not like a Facepager development issue. Could you please ask the question in the Facepager user group on Facebook?
