### ISSUE TITLE
Error: (#10) To use 'Page Public Content Access', your app needs to be owned by a verified business and have contract signed."

### ISSUE THREAD

**Issue by Annika10** [strohne/Facepager#131]
Hi, 

I am very new to Facepager and I only tried a few presets. Last week everything was fine by using these, but today I always getting an error. So I just tried the getting started guide for Facebook and the preset "get facebook posts". In both cases I always getting the following error: 

> {
    "error": {
        "message": "(#10) To use 'Page Public Content Access', your app needs to be owned by a verified business and have contract signed.",
        "type": "OAuthException",
        "code": "10",
        "fbtrace_id": "ASkAl3aRvx0U2Vp8QjwUCtF"
    }
}

I think it is a problem from facebook because scapring from youtube works and last week the getting start from facebook works too. I tried it with another facebook account but it didn't work either. 
Do you have an idea what's wrong with facebook? Do I have to change some settings of my account or something similar? Maybe it is important to say that I had do change my facebook password because of security issues (facebook force me to change).

Thanks in advance.

**Comment by strohne** [comment]
Hi, maybe you need to change the base path to `https://graph.facebook.com/v3.2/`? (By the way, such questions are better handled in the Facepager User Group on Facebook because this is not a development issue.)

**Comment by Annika10** [comment]
My base path is `https://graph.facebook.com/v3.2/` so this doesn't seems to be the problem. 
Thanks for the tip, didn't know about this group. I just check the group and somebody already posted this issue (sadly without a solution yet). I will look there, until somebody has a solution. 
Thanks a lot! :)
