### ISSUE TITLE
Retrieving Texts from Websites

### ISSUE THREAD

**Issue by waleedmandour** [strohne/Facepager#132]
I am trying to retrieve all texts from a News website using the general tab in Facepager app. Unfortunately, I couldn't retrieve anything. Is there some important setting to do for that task?

**Comment by strohne** [comment]
Well, what are your settings? Maybe you could better ask your question in the Facebook group and provide a screenshot there. This way others can participate. We try to reserve GitHub issues for development issues, not general question about using Facepager.
