### ISSUE TITLE
For Presets the Download Images link leads to Nodes and Keys

### ISSUE THREAD

**Issue by MatthewLGibbons** [strohne/Facepager#133]
For Presets the link on 'Download Images' leads to Placeholders. In contrast, for 'Get Comments' the equivalent link leads to the available fields for comments. I wonder if the wrong link is in 'Download Images' currently. If not, where do I find the available fields for images?

**Comment by strohne** [comment]
I think the link is correct. Images are addressed by URLs to be found in the previously fetched data. Thus, you first need to find out which of your fields contains the URL. In the case of Facebook posts, the URLs are given in the attachment or picture fields if I remember it right.  There are no fields in images (and this is not Facebook specific).
