### ISSUE TITLE
'Shiboken.ObjectType' object is not iterable on linux

### ISSUE THREAD

**Issue by adelgado7** [strohne/Facepager#137]
python3 Facepager.py
Traceback (most recent call last):
  File "Facepager.py", line 36, in <module>
    from datatree import *
  File "/home/adelgado/Downloads/Facepager/src/datatree.py", line 309, in <module>
    class TreeModel(QAbstractItemModel):
TypeError: 'Shiboken.ObjectType' object is not iterable

**Comment by jobdiogenes** [comment]
I get the same problem, after some dig, I found that its a problem with install of datatree module its not really compatible with python3, due something StringIO.

**Comment by mrmvergeer** [comment]
I have the same issue, and see that installing datatree indeed gives an error. See Below. Any indication whether this can be solved?

`ERROR: Command errored out with exit status 1:
     command: /home/mrmvergeer/Facepager/pyenv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-u1tkfik2/datatree/setup.py'"'"'; __file__='"'"'/tmp/pip-install-u1tkfik2/datatree/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-u1tkfik2/datatree/pip-egg-info
         cwd: /tmp/pip-install-u1tkfik2/datatree/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-u1tkfik2/datatree/setup.py", line 4, in <module>
        from datatree import VERSION
      File "/tmp/pip-install-u1tkfik2/datatree/datatree/__init__.py", line 1, in <module>
        from .tree import Tree, n, Node, Name, __
      File "/tmp/pip-install-u1tkfik2/datatree/datatree/tree.py", line 1, in <module>
        from StringIO import StringIO
    ModuleNotFoundError: No module named 'StringIO'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by strohne** [comment]
Hi. Not sure where this comes from but I guess it is related to incompatibility between Python 3.8 and PySide2. I suggest you create the pyenv with Python 3.7...see https://github.com/strohne/Facepager/issues/128 for a related issue. Does this work?

**Comment by strohne** [comment]
Can you please try: `pip3 install PySide2==5.14.2` ?

**Comment by strohne** [comment]
I close the issue since there are no updates.  The problem can probably be solved by installing the above mentioned package. Feel free to reopen the issue if necessary.
