### ISSUE TITLE
Can't fetch data using Graph v3.2

### ISSUE THREAD

**Issue by asbestobd** [strohne/Facepager#139]
I am a new user of facepager and I wanted to crawl public data from facebook for my thesis work...This is my error msg:

"This endpoint requires the 'pages_read_engagement' permission or the 'Page Public Content Access' feature or the 'Page Public Metadata Access' feature"

**Comment by strohne** [comment]
Are you sure you are on v3.2? Should work up to v4.0. 

Please ask such questions in the Facepager User group on Facebook. For now, I close the issue since this is a question about using the Facebook API and not directly related to the development of the program.
