### ISSUE TITLE
there is no URL given in login with facebook

### ISSUE THREAD

**Issue by mashaelalenezi** [strohne/Facepager#140]
hello i tried to log in with Facebook to get the access but it's not working. it only appears like this without the access being token

 
![image](https://user-images.githubusercontent.com/74266227/98937345-51090600-24f7-11eb-9b34-31678665dafb.png)

**Comment by strohne** [comment]
Hi...can you try the latest version (pre-release)?

**Comment by strohne** [comment]
I close the issue since there are no updates.  In the meantime, the login process was revised. Feel free to reopen the issue if necessary.

**Comment by strohne** [comment]
Found the error and hopefully fixed it. Credits go to a very helpful user at the #SMARTDatasprint 2021. Try out the new version.
