### ISSUE TITLE
SSL certificate error

### ISSUE THREAD

**Issue by strohne** [strohne/Facepager#141]
![image](https://user-images.githubusercontent.com/69581157/99375418-00612680-28c4-11eb-9854-971419abf2bd.png)

Hi I get a similar but different error, and I have tried it on multiple different networks now. I have also tried deleting the FacePager folder and reinstalling the .exe

I believe there is something wrong with my SSL certificate, but i do not know what, please help

_Originally posted by @JonasBjerg in https://github.com/strohne/Facepager/issues/111#issuecomment-728822436_

**Comment by strohne** [comment]
Maybe this comes from old certificates bundled with Facepager. I will try to update in the next days, please allow some time.

**Comment by strohne** [comment]
Hi, can you try out the latest release v4.3.1? Hopefully, the SSL certificate is updated now. But I'm not fully sure about the error source.

https://github.com/strohne/Facepager/releases

**Comment by JonasBjerg** [comment]
I still get the same exact error, but i think it's a local computer issue now, because I don't get the issue on my mac..

**Comment by strohne** [comment]
Then let's try something different. Looks like your computer doesn't have correct certificates installed or Facepager doesn't find the certificates. 

You will find the certificate file in the installation folder of Fecepager, for example: `C:\Program Files (x86)\Facepager\certifi\cacert.pem`. You can try to add the certificate to windows. Make a copy of the file, change the file extension from pem to crt. Double click and in the certificate window choose to install the certificate.

**Comment by strohne** [comment]
I close the issue since there are no updates and it looks like a local problem.
