### ISSUE TITLE
Cannot open the app Version 4.3.3 on mac

### ISSUE THREAD

**Issue by rungnapantkchk** [strohne/Facepager#142]
At the beginning, I use the 4.2 version to retrieve fb posts and reactions from a page and it worked like a charm.
but, recently, I tried using your app again but i couldn't get 'angry' reaction.
so I looked up for a new version or something.
I successfully downloaded the newest version 4.3.3.
However, I cannot open the application version 4.3.3 at all.
I can still open the Version 4.2 without problem.

Please help

**Comment by strohne** [comment]
Hi! Are you on Windows or on Mac?

**Comment by rungnapantkchk** [comment]
Hello! :)

I am using Big Sur version 11.1.

The Facepager version 4.2 can be opened without problem though.
Only the newest version 4.3.3 that is having the issue. 

There is no error message at all. 
It just froze. When I forced quit the programme. 
There was *the attached picture* a message saying 'Application Not Responding'.
![IMG_9506](https://user-images.githubusercontent.com/73676801/103317546-c3905f80-4a2b-11eb-8885-59ce8edcfde0.jpeg)

Thank you

**Comment by strohne** [comment]
Well, since I'm not a Mac user I use good old HighSierra in a virtual box to create the releases. I guess there are some incompatibilities with newer mac versions.

Are you familiar with the terminal/command line? If yes: could you please open a terminal and start Facepager from the terminal? At best, some error messages occur in the terminal. And can you check whether there is a log file in the Facepager folder in your home dir?

**Comment by rungnapantkchk** [comment]
I have tried open Facepager from Terminal but the same problem occurred.
Not responding TT

When I forced quit the app, this message appeared.
https://1drv.ms/t/s!As9WQTquNY3EgroG0UFmy2Iy6VBE6Q
(this is the .txt file)

**Comment by strohne** [comment]
Hi, maybe I found a solution...it might come from an update. Can you please try out in the terminal:

`export QT_MAC_WANTS_LAYER=1`

...and then try to start Facepager? If this works I will try to bundle the fix with the next release.

(Thanks to https://forums.macrumors.com/threads/pyqt5-and-big-sur.2260773/ )

**Comment by strohne** [comment]
Hi @rungnapantkchk ! I hopefully fixed the issue, can you please try out the latest version 4.3.4? Thanks!

**Comment by rungnapantkchk** [comment]
Hello @strohne 
Sorry that I didn't reply you earlier.
Your latest version 4.3.4 works like a charm ! !
Thank you so much !
