### ISSUE TITLE
Google - Couldn't sign you in

### ISSUE THREAD

**Issue by mzwitter** [strohne/Facepager#145]
Issue: Trying to get data from Youtube videos, however I am unable to log into Google. I can type in my email address, but after that the login form says "Couldn't sign you in. This browser or app may not be secure. Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in." I do not get to the stage where I could input my password.
I have disabled 2FA, enabled less secure apps in my google account and tried reloading the login form, but none of these solved the issue. Is there a workaround (maybe some way to open the login form in chrome, which google treats as secure)?
Sorry if this was reported before, I could not find any thead on this. 

Expected behaviour: After inputting the email address the form should ask me for password and allow login.

Actual behaviour: After inputting the email address the form says browser is insecure and does not allow to proceed.

Context: Windows 10, facepager 4.3, 2 factor authetication disabled, allow less secure apps enabled

Current Workaround: None

**Comment by strohne** [comment]
Hi, Google disabled login with embedded browsers. Please try: In the settings, next to the login button, set authorization to OAuth2 External. Does this help?

**Comment by mzwitter** [comment]
Hi,
Thanks, it did!

But I still cannot complete the login, apparently for a different reason. After inputting the email address and password it asks me for permissions. When I click allow I get a 404 error:
"This localhost page can't be found. No webpage was found for the web address: http://localhost:57597/?code=4/0AY0e-g6JFWZQynAqOixo3KQNwjj0WGXOP85Hejdhal3Tb4BErLbPa90ttkPYD9kpMGoOJw&scope=https://www.googleapis.com/auth/youtube%20https://www.googleapis.com/auth/youtube.readonly%20https://www.googleapis.com/auth/youtube.force-ssl
HTTP ERROR 404"

The status log in the Facepager says:
"2021-02-19 17:45:56.110580 Login server stopped.
2021-02-19 17:45:56.116582 Login server listening at http://localhost:57597.
2021-02-19 17:47:12.070839 Exception: Could not retrieve user ID. Check settings and try again."

It happens on Chrome, Firefox and Edge. 
My google account says Facepager has access to Youtube, but when I try to fetch data in Facepager it says "Your are not authorised, login please!"

I feel like I'm doing something completely wrong, but I just can find a solution to it. 
Thanks in advance for any suggestion.

**Comment by strohne** [comment]
Honestly, I'm not sure why it doesn't work. Maybe some old settings interfere. Can you clear all the settings (More settings->Clear settings when closing -> Restart Facepager), load a blank preset and try to login? What puzzles me is the order of the log: the server ist stopped and then listening? Should be the other way round.

**Comment by mzwitter** [comment]
Thanks fot the help. Unfortunately clearing the settings did not help. 
You are right about the order of the log, that was my mistake. Actually the first time I try (after opening Facepager) there is no "login server stopped". It only appears when I try to login again (immediatelly after clicking "Proceed" in the "Login to Facepager" dialogue) and it apparently stops the previous process.

Here is the complete log of two attempts:
"2021-02-20 16:26:11.068576 Default API definitions downloaded from GitHub.
2021-02-20 16:26:26.119806 Default presets downloaded from GitHub.
2021-02-20 16:26:41.841476 Login server listening at http://localhost:50810.
2021-02-20 16:26:50.036044 Exception: Could not retrieve user ID. Check settings and try again.
2021-02-20 16:29:57.116678 Login server stopped.
2021-02-20 16:29:57.122618 Login server listening at http://localhost:50840.
2021-02-20 16:30:10.245751 Exception: Could not retrieve user ID. Check settings and try again."

**Comment by strohne** [comment]
Thanks. I will try to improve the error output in the next days so we can see what's actually going on. The error indicates that you correctly logged in but nonetheless can't connect to the API.

**Comment by strohne** [comment]
Hi, could you check one of your settings (next to the login button): is the scope field blank?

**Comment by mzwitter** [comment]
Hi, no, it says: "https://www.googleapis.com/auth/youtube https://www.googleapis.com/auth/youtube.readonly https://www.googleapis.com/auth/youtube.force-ssl"

**Comment by strohne** [comment]
And you still can't login, right?

**Comment by mzwitter** [comment]
That's right, still the same as before.

**Comment by pepegito** [comment]
I had the same problem, bit it worked until I selected the right account where I have a Youtube Channel

**Comment by strohne** [comment]
> I had the same problem, but it worked after I selected the right account where I have a Youtube Channel

That's really good to know since I couldn't tackle the problem by now. That makes sense.

**Comment by Glorifier85** [comment]
Hi everyone, 

since this hasn't been closed yet, I just wanted to add that I have been able to fix the exact same issue by simply adding a Youtube channel to my Google account. This is just one click away and available in the settings menu. Logging in and getting the access token now works for me. @strohne I think adding a corresponding note to the release notes/wiki would help people. 

Thanks

**Comment by mdellias** [comment]
Yes, same here. I can't login to Google for YouTube module

**Comment by strohne** [comment]
Hi @mdellias , did you try the solution of Glorifier85?
