### ISSUE TITLE
Add Nodes 

### ISSUE THREAD

**Issue by Pi432** [strohne/Facepager#146]
Hi, 
I am trying to use Facepager to scrap posts from public FB pages. However, the Add nodes botton is not working and therefore I cannot start the operation. Can you help me with this? Thanks in advance

**Comment by strohne** [comment]
Hi, seems like a a question about using and not about developing Facepager, can you please ask in the Facebook group? And the Getting Started sections in the wiki might help. I assume you didn't create a database.

**Comment by elaiesti** [comment]
hi, I can't add nodes in facepager because the Add nodes button is not working and I cannot start the operation. Can you help fix this matter?? Thank you!

**Comment by strohne** [comment]
Please, ask such questions in the Facepager user group. And have a look at the tutorials in the wiki, and make sure you first created a database.

**Comment by caglartasar** [comment]
Hi, I have also same problem for twitter. Do I make something wrong?

**Comment by strohne** [comment]
Please, first create a database. And then... May I ask you to ask such questions in the Facepager user group?
