### ISSUE TITLE
"type field is deprecated for versions v3.3 and higher"

### ISSUE THREAD

**Issue by raulnunescis** [strohne/Facepager#147]
I tried to fetch data from Facebook pages and got this message: 
Error 'error (400)' for secretaria.saude.rio with message (#12) type field is deprecated for versions v3.3 and higher.

Is it something with Facepager and the Graph API version? Or just my computer?

**Comment by strohne** [comment]
Well, I guess this relates to the API version. As v3.2 was discontinued all presets should be upgraded to v3.3. I didn't check it myself, did you look up the reference for v3.3?

Please be aware, in the future, Facebook access is not guaranteed to work with Facepager anymore. There are some radical changes in the Facebook policies that might have stark consequences for Facepager not too long from now.

**Comment by Glorifier85** [comment]
Hi @strohne, 

I hope you don't mind me asking: Are these changes in the fb policies you mentioned going to affect the possibility to fetch Fb posts in general or is it just affecting Facepager at the moment? I am in the middle of a research project for which I use Facepager. Not having access to the feed of selected fb pages would be bad news for me :(
Many thanks in advance!
