### ISSUE TITLE
Failure when login to Facebook

### ISSUE THREAD

**Issue by gskarp** [strohne/Facepager#148]
When trying to Login to Facebook, while initially I get a message "Success", then I get an error message as in the image. Any attempt to fetch the data ends to a "You are not authorized, login please!" message.

Any suggestion?

<img width="603" alt="image" src="https://user-images.githubusercontent.com/6851894/117574738-2b943800-b0e7-11eb-90c8-1b1457b751c3.png">

**Comment by strohne** [comment]
Hi! Is this solved in the latest release?
