### ISSUE TITLE
Failed to execute script for version 4.3.11

### ISSUE THREAD

**Issue by ghost** [strohne/Facepager#149]
I tried to download the latest version 4.3.11 from this site, https://github.com/strohne/Facepager/releases 
It's now on my PC. I tried to run it- it did, I can now see the Facepager button on my desktop, but when I try to open it, a dialogue box appears which says 'failed to execute script'. At this point, I don't know how to trouble shoot this. Is it because 4.3.11 is the new version and there are unfixed bugs? Help.

**Comment by AidenYeh** [comment]
I downloaded the 4.3.10 version- and it was a success! Using it now.
So I reckon, bug fixes are needed for the new 4.3.11 version

**Comment by strohne** [comment]
Thanks for pointing this out. Are you on Windows or Mac?

**Comment by AidenYeh** [comment]
Hi
Im using my PC (I’m afraid I’d have difficulty downloading with my Mac)

Anyway, I’m able to use 4.3.10. Im following Dr Chan’s tutorial on fetching FB data but my first try was unsuccessful. I’m now on my 5th try.

I wanted to fetch the comments from The EConomists FB page on its post on Taiwan as a dangerous country. I also want to collect Twitter comments on the same post. But I’m working on FB comments first. 

My aim is to analyze the comments and run a corpus analysis of both the article and the comments. 

Anyway, I’m not a programmer- so doing this is really difficult. 

Thanks for the help- 

Aiden Yeh, PhD 
Associate Professor 
English Department & Graduate Studies
Wenzao Ursuline University of Languages  Kaohsiung, Taiwan  
Tel: +886-7-3426031 ext. 5336  
E-mail: ***@***.***TwitterID: motherchina 
SkypeID: aidenyeh Line, Talkbox, Viber: +886938392852

**Comment by strohne** [comment]
Hi @AidenYeh if you have questions about using Facepager, see our Facebook user group. You don't need top be a programmer, nothing to program when using Facepager, this is a point and click adventure :)

To you original problem: the PC where the error occurs is a Windows PC? Which Windows version?

**Comment by AidenYeh** [comment]
Hi

Im using Windows 10 pro versión 2004 on Asus.

Thanks

**Comment by strohne** [comment]
Strange, works for me. I will investigate the case.

Btw, regarding GitHub: maybe you want to remove your personal information from the issues page?

**Comment by AidenYeh** [comment]
Ok- thanks for advice on removing personal info on GitHub.

Another thing, can you create a tutorial on saving comments on Twitter post? I can’t seem to find any. I saw one on fetching photos from Twitter- but I’m interested in getting the comments.

Thanks.



Aiden Yeh, PhD 
Associate Professor 
English Department & Graduate Studies
Wenzao Ursuline University of Languages  Kaohsiung, Taiwan  
Tel: +886-7-3426031 ext. 5336  
E-mail: ***@***.***TwitterID: motherchina 
SkypeID: aidenyeh Line, Talkbox, Viber: +886938392852

**Comment by strohne** [comment]
Please ask such questions with regard to using FP in the group. The issue system should only be used for development issues. I suggest you get familiar with the Twitter API in order to find out yourself: FP is made for learning API stuff :)
