### ISSUE TITLE
Commercial use

### ISSUE THREAD

**Issue by ezequias** [strohne/Facepager#151]
Hi @strohne 

Could you tell me about the commercial use of your solution? We can use it for a long time period of time without any complications?

I guess your project is focused on academic purposes. Am I correct about that?

Thank you
Ezequias

**Comment by strohne** [comment]
Yes, Facepager is made for academic purposes. And there is no guarante that the inbuilt access to Facebook, YouTube or Twitter will work tomorrow - this depends on the platforms. Further, check the developer policies of the APIs you want to use - some use cases are prohibited by the API providers (e.g. no long-term monitoring of FB data).
