### ISSUE TITLE
application  not working on win 10 32

### ISSUE THREAD

**Issue by Amr-Eissa** [strohne/Facepager#152]
dear my friend 
I try to run the application but not working on win 10 32 bit .plz can help my 
![021212](https://user-images.githubusercontent.com/32038452/120045241-cfe70b80-c00f-11eb-9d90-f5f3d5d60fd7.JPG)

**Comment by strohne** [comment]
Sorry, we don't have the resources to supply 32bit support. Anyway, you can run Facepager from source (see the home page) if you don't need the predefined access to Facebook, Twitter, or YouTube. In case you have your own API access, you can use Facepager with that.
