### ISSUE TITLE
version number is 0.0.0 and not 4.3.10

### ISSUE THREAD

**Issue by core-code** [strohne/Facepager#153]
<img width="591" alt="Screenshot 2021-05-31 at 00 37 17" src="https://user-images.githubusercontent.com/1261954/120122330-7403ba80-c1a8-11eb-90a7-6cd56cd929e8.png">

**Comment by strohne** [comment]
Perpetual zero :) This comes from the installer, one day I will fix it. And reducing the much too large file size is on the agenda as well.
