### ISSUE TITLE
Problem to export data to csv

### ISSUE THREAD

**Issue by bfPol** [strohne/Facepager#154]
Hi!
I'm using Facepager to extract some posts from Facebook and I'm having trouble exporting data to csv. I've followed all the steps of the tutorial and I've collected the posts successfully, but when I try to export the data, nothing happens. I save the file, but the "exporting data" window does not appear, nor does the file that I had saved appear. How could I solve this problem?
Thanks! :)

**Comment by strohne** [comment]
Is this solved by now? Maybe you should check: don't use any special characters in your folder or file names.
