### ISSUE TITLE
Cannot Fetch Data with vMix Published Post

### ISSUE THREAD

**Issue by micoevil** [strohne/Facepager#156]
Hi, I am new here and I have encountered a problem in fetching a particular post in Facebook. I have fetched all the posts from a page except one that I want to extract comments. It seems that Facepager didn't recognize the post that have been published using vMix. Is there a conflict with software vMix and Facepager that it cannot recognize the post?

![1ST](https://user-images.githubusercontent.com/10230887/124385781-c422ef00-dd09-11eb-9a88-44ed747c8e01.png)
![2ND](https://user-images.githubusercontent.com/10230887/124385783-c6854900-dd09-11eb-9002-3870e4a49fbc.png)
![3RD](https://user-images.githubusercontent.com/10230887/124385784-c71ddf80-dd09-11eb-8662-89a926c2efbd.png)

**Comment by strohne** [comment]
Hi there, is this a very active page? In case there are more than 600 posts per year, Facebook only provides a sample of post, see the reference of the posts endpoint.

May I ask you to ask such questions in the Facepger user group on Facebook? The GitHub issue system is better used for problems related to the development of Facepager, not for using the app.

**Comment by micoevil** [comment]
Thank you for your response. This is not a very active page and it just
created last year. It has only 150+ posts up to now. I am just wondering
that it cannot fetch the recent post with a software (vMix) published post
and all the posts published by administrators were captured. I just posted
the question yesterday in the Facebook group if there were same issues.
Thank you for your time and consideration.
PS. I am amazed with your software. More accurate and convenient than other
similar softwares.
