### ISSUE TITLE
app not opening

### ISSUE THREAD

**Issue by akimayit** [strohne/Facepager#157]
Hello,

I have downloaded and unzipped the app, but it is not opening.

**Comment by strohne** [comment]
Hi, can you give some more details? Without info about your OS, the specific behavior or maybe some screenshot I have no clue how to hekp or fix it.

**Comment by nabbonabbo** [comment]
hey @strohne, I have the same problem, even though I gave permission to open it. It's Installed on MacOS.

**Comment by strohne** [comment]
Hi @nabbonabbo , and can you give some more details? Which version? What ist the procedure to reproduce the behavior? Best.

**Comment by nabbonabbo** [comment]
Hi @strohne thanks for your fast reply! I tested it in a more recent Mac of a friend and everything works fine there. I guess it was crashing because of my outdated OS, I am running High Sierra Version 10.13.6. Unfortunately, I can't update the OS on my MacAir Mid 2011 :(

**Comment by strohne** [comment]
Huh, sorry, I can't support old Mac versions, my time for producing the builds is very limited. If you know someone who is able and willing to prepare an installer version for High Sierra, let me know.

**Comment by gerickt** [comment]
I have the same problem with Mojave
