### ISSUE TITLE
Login to Facebook Error: Error Accessing the App. Unfortunately the App you are trying to use is either deactivated or doesn't exist (translation from German error message)

### ISSUE THREAD

**Issue by clemwo** [strohne/Facepager#158]
Basically title. Here is a screenshot 
![error message](https://i.imgur.com/8iVmzL2.png)
Im using Facepager 4.3.10 and everytime I try to log in to facebook I get this error message. Its german, roughly translated the error is: 
"Error Acessing the App. Unfortunately the App you are trying to use is either deactivated or doesn't exist."
The green button says "Create Account" but doesnt do anything either.

**Comment by strohne** [comment]
Please see the post in the Facebook group and my tweet: https://twitter.com/jajuenger/status/1428039557946167298
