### ISSUE TITLE
Problems with Facebook  PostsComments 

### ISSUE THREAD

**Issue by cristobalvch** [strohne/Facepager#163]
Hello Strohne, first of all, thanks for this amazing tool.  I have been using it for my research and it's very useful for fast information download.

I'm having issues with Facebook Posts Comments when I try to download comments from posts using presets or API default configuration. I'm just obtaining 1 single comment per post, but some days ago I could download all comments from posts. I just wanted to know what thing it could be creating the problem.
I also reviewed my credentials account and the are not blocked by facebook

**Comment by strohne** [comment]
Hi, we  are currently in the process of releasing a new version and needed to revise some presets and settings. If it works for you, try the latest release 4.4  (although it does not work on all windows systems yet, working on it).

Workaround #1 for pros: I guess all posts are in one node, you can use the Extract data feature to slice them into different nodes.
Workaround #2 for hackers: copy the default Facebook API doc to the custom API doc folder and adjust the key to extract.

**Comment by cristobalvch** [comment]
Ok I'll try with the workarounds, thanks for your help!. I'll be awaiting for the new release

**Comment by strohne** [comment]
@cristobalvch ... I just updated the experimental release for Windows (v4.4). I'd really appreciate if you could try it and reopen the issue if it still doesn't work for you.

**Comment by cristobalvch** [comment]
Sure @strohne  and thanks!. If I have any problem i will open the issue again and notified you

**Comment by cristobalvch** [comment]
Hi @strohne. I tried to follow your advices but unfortunately  now I'm facing problems fetching data of posts and comments in facebook with Facepager 4.3.10. I did tests using presets and api section

Using Facepager 4.4, the applications inmediately close it when I log in on facebook.

So I will have to wait for the official release of Facepager 4.4.

**Comment by strohne** [comment]
Thanks for the feedback and sorry for the crashes ... can you check whether you are on a 32bit or 64bit Windows version?

In the meantime, maybe you'll get some support in the Facepager User Group on Facebook to overcome the limitations of v4.3.10.

**Comment by cristobalvch** [comment]
I'm in 64bit Windows Version.
Sure I'll take a look on Facebook User Group
Thanks again for your support @strohne. I'm glad that there are people like you around the world sharing great tools
kind regards
I will close the issue
