### ISSUE TITLE
cant login facebook

### ISSUE THREAD

**Issue by kirubakaranpalaniyappan** [strohne/Facepager#164]
i cant login facebook its show error as not responding

**Comment by strohne** [comment]
There is a reload button in the login window...does that help?

**Comment by keydogg11** [comment]
Hi I also tried to connect to both facebook and twitter and was droped out of the software

**Comment by brunosndias** [comment]
Hi, I couldn't connect to facebook either, when I tried it, the software ended abruptly.

**Comment by strohne** [comment]
I guess you use the experimental build? This is experimental and not yet fully functional. Can you try an older release?

**Comment by merajhuda** [comment]
Just "upgraded 4.2 to 4.4". Now cannot login to Facebook, it just shuts down.

**Comment by csantanaes** [comment]
Just "upgraded 4.2 to 4.4". Now cannot login to Facebook: login screen pops up without any fields, and then the app just shuts down. same case

**Comment by strohne** [comment]
Hi there, I updated the windows release to version 4.4.1 (you are on Windows?). Could you please try whether it crashes or works on your machines? 

The login window sometimes still is nasty. If it stays blank, close it and retry several times. :)

**Comment by AlbertSharra** [comment]
I am using 4.4.1 but i cant log in to Facebook, it says "Could not authorize for page. Check page ID in the settings" How do I address this?

**Comment by strohne** [comment]
Hi, please use the latest release and check that the settings (button next to login button) are clear.
