### ISSUE TITLE
Can't add new nodes

### ISSUE THREAD

**Issue by bnednbb** [strohne/Facepager#165]
I got the facepager installed on my MacOS, but I cannot add new nodes.

**Comment by bnednbb** [comment]
Installed facepager 4.4 via Python because the normal installation did not work. However, I cant add nodes.

**Comment by strohne** [comment]
Hi, can you be more specific? What happens when you click the add nodes button? And did you create/open a database before?

**Comment by bnednbb** [comment]
The add nodes button is greyed out - so I can't press it. Yes, we tried both creating and opening a database before.

**Comment by strohne** [comment]
Hi! Can you post a screenshot (with the status log, status bar, toolbar)? A have no idea.
