### ISSUE TITLE
 Cannot open the app Version 4.3.10/4.4.0 on Mac 

### ISSUE THREAD

**Issue by gerickt** [strohne/Facepager#170]
Hi guys, im new in facepager...
when i try to open any version of Facepager i get this message:

**"Facepager.app" is damaged and can't be opened. You should move ir to the Trash.**

Any help?, thanks

**Comment by strohne** [comment]
Interesting, what's the purpose of `xattr -cr` (I'm not a Mac user, therefore building Facepager for Mac challenges me every time).

**Comment by strohne** [comment]
I guess this comes from the security mechanisms of mac. Since we don't sign the app (had no time yet), you explicitly have to allow unsigned apps. I'll put signing the app onto my bucket list.
