### ISSUE TITLE
Cannot see full tweets in Facepager 

### ISSUE THREAD

**Issue by MariaTrottner** [strohne/Facepager#172]
Hello, I am new here and I am using Facepager for my Bachelor thesis. I would like to analyze the tweets of politicians. For my analysis I need the whole tweet, but Facepager just gives me a part of every tweet. How can I fix this? 

Screenshot: 
![Bildschirmfoto 2021-10-25 um 15 22 56](https://user-images.githubusercontent.com/93137263/138703564-fae3fc26-b148-4354-8646-afd9367a8e46.png)

Thanks for your help!

**Comment by strohne** [comment]
Hi, as this is related to using Facepager and APIs and not development, may I ask you asking your question in the Facepager user group? There , hopefully, you'll find help.
