### ISSUE TITLE
Issue with the Facebook Get Reactions Presets

### ISSUE THREAD

**Issue by skwolvie** [strohne/Facepager#175]
Hi

The Get Reactions to a post-id presets is not working. Earlier,I was able to populate reactions from posts to a new column. 
Now with the same preset, I'm getting error 400, with the message: # 100 missing permissions.

I tried to find a workaround for this failure with the API option and selecting /<post-id>/reactions/ options.
With this, I get 2 responses populated at Node level 3: 1. an offcut object, 2. an empty object.

The empty object contains nothing. the offcut object contains key-value pairs as shown in screenshot-5.
The /<post-id>/reactions/ API does not take the fields as a parameter. It takes only 2 parameters type, and a summary. the type param can be LIKE, LOVE, SAD,.... and the summary param can be 0 or 1 if it is set to 1, you get the summary key-value pair in the offcut object. Although with this workaround you cannot get all the different type reactions summary count at the same time, it seems to be fetching the count of reactions.

Questions:
1. How to fix the preset to get the output like we were able to obtain earlier?
2. How to extract the total_count from the summary variable of the API response? 
    This type of filtering with field parameter is not supported by the API: reactions.type(LIKE).limit(0).summary(1).as(like) 
    
    I tried to make some modifications to the parameters to get this thing to work. But I was not completely Successful. The last screenshot shows the modifications I did to the params and the output I was getting.

3. How to finally extract all reaction counts associated with a post-id to new columns and export the results to a CSV file?

**I have added the screenshots in the order of traversal of the app below:**

Please share valuable suggestions and inputs.

![image](https://user-images.githubusercontent.com/22741452/141237542-d6a182bd-8ac2-4267-8d51-37edc76cc756.png)
![image](https://user-images.githubusercontent.com/22741452/141237558-671715e4-4378-4345-9b91-35db3cbb5889.png)
![image](https://user-images.githubusercontent.com/22741452/141237574-426a2924-a22a-4784-8879-32bf7c6b6b4e.png)
![image](https://user-images.githubusercontent.com/22741452/141237652-7ab43399-6477-494f-bb66-835f8d70cb7f.png)
![image](https://user-images.githubusercontent.com/22741452/141237946-1d77f448-03a0-496a-a5ef-1a07ef965c12.png)

![image](https://user-images.githubusercontent.com/22741452/141239721-dcf8989a-7a0e-4ee5-9c4b-83fc6900500b.png)

**Comment by strohne** [comment]
Hi @skwolvie , thank you for the detailed description. Since this is an issue about using Facepager and dealing with the Facebook API, may I ask you to ask your question in the Facepager User Group on Facebook? In the GitHub issue system we try to stick to development issues.

Anyways, you should check the API reference of Facebook to get this working. Recent changes may have broken the preset, my first try would be setting the API version to 5.0.

**Comment by skwolvie** [comment]
Hi @strohne, I posted this issue request since I didnt get any response on the facebook's facepager user group. I changed the API version to 5.0 to 12.0 and tested. I was not able to set the 'field', 'as', parameters and also I was unable to get the summary.total_count to a column. 

Just a quick clarification. This issue is also related to the development of the presets right? please do correct me if I'm wrong.

Best,

**Comment by grahesha0100** [comment]
I am facing the same problem.
Any updates/solution to this issue please ?

**Comment by strohne** [comment]
Well, the API changed. If you habe any suggestions, please let me know.
