### ISSUE TITLE
Is it possible to get the tagged pages' URLs when extracting Facebook pages?

### ISSUE THREAD

**Issue by Qiyuuue** [strohne/Facepager#177]
Some public pages are tagged in the posts. I found that the "messgae_tags" could give these tagged pages' names. I want to ask whether it is possible to get these pages' URLs.

**Comment by strohne** [comment]
Hi! May I ask you to ask such questions reagaring the usage of Facepager in the Facebook group? The issue system should better be reserved to devekopment issues. Thanks :)
