### ISSUE TITLE
why the Facepager do not need app review to extract public content

### ISSUE THREAD

**Issue by stefan9903** [strohne/Facepager#180]
Hello! I have a question about the API and related permissions. When I use Graph API Explorer, I found the error saying I need app review to access the posts from other groups. But when I use facepager, I get the data successfully. I wonder why the Facepager do not need app review to extract public content. 
I will really appreciate it if you can reply to me!

**Comment by strohne** [comment]
Hi there, easy question: we have gone through the app review with Facepager and when you use Facepager you use our preregistered app.

**Comment by stefan9903** [comment]
thanks a lot!
