### ISSUE TITLE
Could not retrieve user ID

### ISSUE THREAD

**Issue by staqiuddin** [strohne/Facepager#182]
Hi. I am using the latest version of Facepager (4.3.10) on a Windows 10 machine. I need to retrieve the comments and replies of YouTube videos.

I followed the steps mentioned in https://www.youtube.com/watch?v=1Nt1gJu-hzU. After successfully logging in to my Google account and granting the required permissions to Facepager, I am unable to get an access token when trying "OAuth2" and "OAuth2 External" as authentication types. I have attached the following:

1. Contents of the "Status Log" box.
2. The "facepager" log file found under C:\Users\...\Facepager\Logs.
3. A screenshot of the access granted to Facepager.
4. A screenshot of the error faced when using "OAuth2".

Kindly note that I have consulted https://github.com/strohne/Facepager/wiki/Login-and-Access-Tokens as well as similar registered issues but to no end.

[Status log.txt](https://github.com/strohne/Facepager/files/8185269/Status.log.txt)
[facepager.log](https://github.com/strohne/Facepager/files/8185271/facepager.log)
![Facepager granted access](https://user-images.githubusercontent.com/41196751/156752638-aa53f3c2-585c-43ed-ae2a-b0cd6a43d389.png)
![OAuth2 error](https://user-images.githubusercontent.com/41196751/156751517-9527f122-bfd1-475e-b3a4-04b7104fec73.png)

**Comment by strohne** [comment]
Hi, we updated the release, please try the latest version.
