### ISSUE TITLE
Facebook graph api v3.2 broken

### ISSUE THREAD

**Issue by terrok9** [strohne/Facepager#183]
Getting information from public pages is harder in your last build.

Let's see an example:

Putting a specific seed as Object ID is as usual and works as usual. However, when you fetch data from the path /<page-id>/posts, it returns paging nodes, not data object keys or data nodes.

It would be great if you can show us how to recover an organized database as it used to be.

I will attach some workarounds.

Picture before last build:

![image](https://user-images.githubusercontent.com/67476075/157834839-88f29b0e-c7ec-4722-a40a-33beb25e4153.png)

Picture cn the current build:

![image](https://user-images.githubusercontent.com/67476075/157834746-74ed9015-4c2e-4c59-a81c-c7e9e8b4fc8f.png)

Thank you soo much.

**Comment by strohne** [comment]
Hi there...the Graph API v3.2 unfortunately is outdated. If you use the latest Facepager version and/or update the base path to v13 it should work as usually. Can you confirm this?

**Comment by terrok9** [comment]
Hello!
 
Thank you for your answer.

I am following the same steps using the v13, this is to generate a db where you can observe each element of the node 2 as a list of posts, just like the first image that I uploaded.

Is not working as usual due to the fact that it recovers all the posts as a column of the dataframe and puts paging information as relevant data of node 2.

Are we able to recover the same structure that we did recover in v3.2? (posts by post db) Or we should simply process this data externally knowing that is harder to extract per post information.

Thank you in advance for your help.

**Comment by strohne** [comment]
Sorry, we can't reproduce this. The latest version of FP with the Facebook API base path including version 13 should work. Maybe you can ask the question in the Facepager user group on Facebook and provide step by step instructions how to reproduce the issue?
