### ISSUE TITLE
login to Facebook

### ISSUE THREAD

**Issue by keydogg11** [strohne/Facepager#185]
Hi,
I'm keep receiving this message: You can't log in to this app or website because you do not meet the requirements for country, age or other criteria.
I tried on different computers with different versions of Facepager.
What to do?
Thank you

**Comment by strohne** [comment]
Please see the Facebook group :)

**Comment by keydogg11** [comment]
Thank you Jacob, I did.
Omer

**Comment by keydogg11** [comment]
Hi Jacob,
I did send you a request to unlock Israel on the Facebook group. My
students needs to use Facepager as their assignments next week.
Can you please unlock Israel?
Thank you,
Omer

בתאריך יום ד׳, 18 במאי 2022, 15:13, מאת Omer Keynan ***@***.***>:

**Comment by strohne** [comment]
Hi @keydogg11 ... thank you for the reminder :) We are checking the group only in intervals, I unlocked it one moment ago. Does it work?

**Comment by keydogg11** [comment]
Thank you Jacob,
But now I'm receiving an error message.
See attached.
Omer

**Comment by strohne** [comment]
Hi, I don't see the attachment...you can contact me by my university mail if you want? I try to respond soon, but at the moment I'm in a hurry.

**Comment by keydogg11** [comment]
Sorry, the message is: "could not authorize for page. check page ID in the
settings."

**Comment by strohne** [comment]
Sorry, this is too vague...I suggest you go into the Facebook user group and post a screenshot. I'll ask our student moderators to reply soon and will look at it tomorrow morning, ok?

**Comment by keydogg11** [comment]
thank you very much

**Comment by keydogg11** [comment]
I uploaded the photo, thank you again!
