### ISSUE TITLE
(#12) Open Graph action get is deprecated

### ISSUE THREAD

**Issue by mathieuchateau** [strohne/Facepager#186]
Hello,
I have this error when trying to get post comment through preset:

{
    "error": {
        "message": "(#12) Open Graph action get is deprecated",
        "type": "OAuthException",
        "code": "12",
        "fbtrace_id": "xxxxxxx"
    }
}

Any clue ? Tried version 4.4 and 4.3.10, same result.

**Comment by strohne** [comment]
Hi, please ask such questions about how to use Facepager and the Facebook API in the group. I guess this has something to do with the settings.
