### ISSUE TITLE
Log in issue

### ISSUE THREAD

**Issue by JackRyan85** [strohne/Facepager#187]
Hello,
I downloaded the latest version for windows. Unfortunately I can't log in with my Facebook account. Does anybody know what could be the problem? Can you log in from just some specific countries?
Thanks!
PS. I tried with an earlier version as well, and I have the same problem.

**Comment by Bluestone69** [comment]
Hello,
I've experienced the very same problem. Have you tried it in the Face Pager Users group on fb too?

**Comment by strohne** [comment]
Hi, we temporily had to block login, see the discussion in the Facepager User Group. By now, everthing should be resolved.
