### ISSUE TITLE
Errors on Facebook data retrieval

### ISSUE THREAD

**Issue by Mpellet771** [strohne/Facepager#190]
I am trying to download both reactions and comments for a Facebook page and get this error: 
(#100) Tried accessing nonexisting field (comments) on node type (Page)

and
"id"	"parent_id"	"level"	"object_id"	"object_type"	"object_key"	"query_status"	"query_time"	"query_type"	"message"	"created_time"	"like_count"	"comment_count"	"error.message"
"107"	"1"	"1"	"TCHFH"	"data"	""	"error (400)"	"2022-08-18 12:08:16.686964"	"Facebook:/<post-id>"	""	""	""	""	"(#100) Object does not exist, cannot be loaded due to missing permission or reviewable feature, or does not support this operation. This endpoint requires the 'pages_read_engagement' permission or the 'Page Public Content Access' feature or the 'Page Public Metadata Access' feature. Refer to https://developers.facebook.com/docs/apps/review/login-permissions#manage-pages, https://developers.facebook.com/docs/apps/review/feature#reference-PAGES_ACCESS and https://developers.facebook.com/docs/apps/review/feature#page-public-metadata-access for details."

When I use the <APIs> links it does not help. 

Also, Facebook GraphAPI is on v. 14 now -- is that part of the issue or am I missing a step? I do download the posts first.

**Comment by strohne** [comment]
Cheers! I think you mixed up the levels. Pages don't have comments, only posts. May I ask you to ask such questions in the Facepager User Group? GitHub issues should better stick to development issues.
