### ISSUE TITLE
Pagination for Twitter Timeline (API v2) not working

### ISSUE THREAD

**Issue by qd1990** [strohne/Facepager#191]
Hi, I am using the User Tweets Timeline (Twitter API v2) to collect tweets of a public brand. The objective is to collect the most recent 3200 tweets of a brand. My setting is shown in the attached screenshots. However, I cannot figure out how to make the pagination work so that I can collect all the 3200 tweets without manually updating the pagination_token again and again. 

I tried to enter "meta.next_token" in the pagination_token, however, I got an errod which says: "The `pagination_token` query parameter value [meta.next_token] is not a valid token." If I manually enter the meta.next_token value, I can keep collecting the next page of tweets, but this takes a lot of time as I have to re-enter the next_token value again and again. 

I tried to search to see if there is any instruction on this, but cannot find. So I am wondering if anyone could give me some guidances on how to do this. Thanks for your time and consideration! 

<img width="712" alt="Screenshot 2022-08-23 093012" src="https://user-images.githubusercontent.com/61234804/186160481-a91f0fab-1776-40c6-8bee-20babf48ec12.png">
<img width="722" alt="Screenshot 2022-08-23 093040" src="https://user-images.githubusercontent.com/61234804/186160492-34c4c90c-6e0e-4925-bda8-4f07b0a556dd.png">
<img width="960" alt="Screenshot 2022-08-23 094211" src="https://user-images.githubusercontent.com/61234804/186160761-dc114146-3dff-46e8-856f-a80bcebf9bea.png">

**Comment by strohne** [comment]
Thanks for the detailed description. We will fix this, please allow some time,

**Comment by strohne** [comment]
Should work by now, without reinstalling Facepager, just restart it. I added the pagination info to the API doc https://github.com/strohne/Facepager/blob/master/apis/Twitter.v2.oa3.json

Please, could you try it out?
