### ISSUE TITLE
Facebook page Vs Public Facebook Account

### ISSUE THREAD

**Issue by AlbertSharra** [strohne/Facepager#194]
I am using the latest version of Facepager 4.4. However, I am unable to fetch data from public facebook account. I am able to fetch data from a Facebook page. Is there a way I can capture posts on the public Facebook account?

**Comment by strohne** [comment]
Hi @AlbertSharra ... may I ask you to ask the question in the Facepager user group? The GitHub issues are reserved for development issues :)
