### ISSUE TITLE
Empty Node Fetched When I Try to Parse Facebook Posts

### ISSUE THREAD

**Issue by GrimesSheenaLana** [strohne/Facepager#197]
Hello! When I tried to parse the posts from Facebook, I kept getting an empty node that had no data. There was no error or issue raised from Facepager. The Facepager page is attached. Please feel free to help or respond if you have encountered similar issues, thanks a lot!

<img width="1094" alt="Screen Shot 2022-10-11 at 19 15 05" src="https://user-images.githubusercontent.com/96779054/195077470-126f8714-dcfc-4da3-9fe0-31665f9ea5fe.png">

**Comment by isklee** [comment]
Hey there, I don't know if you still need a solution for your problem, but it seems to be connected to the transition of some pages to the New Page Experience. Here you can see our post about this (https://www.facebook.com/groups/facepagerusers/permalink/923759074908619/).
