### ISSUE TITLE
Error message when  i tried to fetch facebook comment from public page

### ISSUE THREAD

**Issue by Alaa-Brihi** [strohne/Facepager#199]
I am a new user of facepager and I wanted to crawl public comments data from public facebook page for my phd thesis work. But I cant fetch data because of missing permission or reviewable feature, or does not support this operation. How can solve this problem ??

**Comment by isklee** [comment]
Hey there, I don't know if you still need a solution for your problem, but it seems to be connected to the transition of some pages to the New Page Experience. Here you can see our post about this (https://www.facebook.com/groups/facepagerusers/permalink/923759074908619/).
