### ISSUE TITLE
Extract Posts and Comments from Political Party Page

### ISSUE THREAD

**Issue by asul2** [strohne/Facepager#202]
Hello, 

I am new to Facepager and am using the software for the first time in my Online Communities Course. I am unable to extract posts and comments from the Team Trump Facebook page and have tried the same with the Bernie Sanders Facebook page. The software works great with the Hong Kong Science Park Facebook page https://www.facebook.com/HongKongSciencePark/ as featured int this tutorial https://www.youtube.com/watch?v=b2rUxb3X4ho. 

The Hong Kong Science Park Page looks like this...
![image](https://user-images.githubusercontent.com/103225711/218554012-6be2243f-1821-4e1a-b88d-695758c24572.png)

The Bernie Sanders page: https://www.facebook.com/berniesanders
![image](https://user-images.githubusercontent.com/103225711/218554222-b24e6a37-a824-4d9b-9fd8-c566954d6d37.png)

The Team Trump page: https://www.facebook.com/officialteamtrump
![image](https://user-images.githubusercontent.com/103225711/218554384-a439a4f0-563c-47cd-a585-103e5dd24628.png)

Here is the query I get after fetching data for the Hong Kong Science Page: 
![image](https://user-images.githubusercontent.com/103225711/218554571-01a54dd4-9ed7-483c-9859-abb757fc56dc.png)

Here is the query I get after fetching data for the Team Trump Page (looks the same for the Bernie page): 
![image](https://user-images.githubusercontent.com/103225711/218554888-92c99d99-94a6-4091-a881-fa6a83ad2ab2.png)

As you can see, there is no messages being fetched/produced by the Team Trump page, how can I retrieve the posts and comments subsequently.

Thank you very much,

**Comment by isklee** [comment]
Hey there, I don't know if you still need a solution for your problem, but it seems to be connected to the transition of some pages to the New Page Experience. Here you can see our post about this (https://www.facebook.com/groups/facepagerusers/permalink/923759074908619/).
