### ISSUE TITLE
Unable to create new database

### ISSUE THREAD

**Issue by ziqizhang** [strohne/Facepager#203]
Hi

I am trying to use Facepager on Ubuntu 22.04. I installed it following the instructions and started the app. When add a new databse, I get this error:

Invaild argument(s) 'convert_unicode' sent to create_engine() using configuration SQLiteDialect_pysqlite/QueuePool/Engine. Pleaes check that the keyword arguments are appropriate for this combination of components

Also, my twitter login page is showing 'loading' all the time without progressing.

Any help please

**Comment by etlfg** [comment]
Same on Debian 5.9.6-2parrot1

**Comment by catwolfman** [comment]
Dear @ziqizhang, we have updated the conflicting code to match current package versions. The same issue appeared on macOS Sonoma 14.5. Please, pull the latest changes and try to run Facepager from source again. [LH]
