### ISSUE TITLE
error while fetching data while trying to get datas from a public page

### ISSUE THREAD

**Issue by ihabpalamino** [strohne/Facepager#204]
Error 'error (400)' for userID with message Unsupported get request. Object with ID 'userID' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api.

**Comment by isklee** [comment]
Hey ihabpalamino, I don't know if we understood you correctly... but why are you using the userID? What are you trying to fetch? If you want data from public pages you should use the page ID.
