### ISSUE TITLE
Facepager Facebook error 400

### ISSUE THREAD

**Issue by evaoa** [strohne/Facepager#205]
Hi there, I've been using Facepager for the past few weeks but took a break from it for about 1 week. I went back to using it today, however, when I did everything I did in the past including the correct fields, etc. 'error 400' kept on appearing. I would like to know whether this is a temporary glitch or whether I am doing something wrong or inserting something strange. Thanks (image is attached)
<img width="1092" alt="Screenshot 2023-05-02 at 18 11 41" src="https://user-images.githubusercontent.com/131674998/235723726-b4026e16-9cc7-4a78-a8d5-56e9bed83304.png">

**Comment by isklee** [comment]
Hey evaoa, could you please provide the error message and/or the full Object ID? Our guess is, that this is connected to the New Page Experience (https://www.facebook.com/groups/facepagerusers/permalink/1212115399406317)
