### ISSUE TITLE
Only 26 nodes fetched

### ISSUE THREAD

**Issue by 13ouncyKnight** [strohne/Facepager#206]
2023-06-10 10:13:47.483223 Fetching completed, 26 new node(s) created. Summary of responses: 1 x fetched (200).

Is there a way I can get 1460 nodes from a particular Facebook page?

**Comment by isklee** [comment]
Hey there, please post your problem in our usergroup on Facebook (https://www.facebook.com/groups/facepagerusers). Maybe you can give us more specific information about what you want to fetch (1460 posts?) & screenshots of your query.
