### ISSUE TITLE
Wrong text encoding 

### ISSUE THREAD

**Issue by lukasini** [strohne/Facepager#209]
I´m facing issue with encoding symbols š,č etc. when scrapping slovak pages. I guess this is limitation of SQLite that supports only ISO-8859-1. Also exporting to UTF8 change nothing. Do you have some workaround or better way to fix it?

Within application it is looking fine but inside database its encoded wrongly
<img width="728" alt="1" src="https://github.com/strohne/Facepager/assets/24207782/64d4d468-232d-4ca4-ae86-725ac424aef7">
<img width="650" alt="2" src="https://github.com/strohne/Facepager/assets/24207782/cb6114c1-cd7e-4c11-843e-305a22a6aa6e">

**Comment by strohne** [comment]
Hi lukasini, I guess the encoding is correct but you need to handle it in your subsequent workflows. How do you process the data? When you export a csv file, does it come out with the right encoding? 

For R, we have an experimental package that loads the database, maybe it helps you? See https://github.com/strohne/datavana/tree/main/facepager

**Comment by strohne** [comment]
I suggest you use the export button of Facepager, that handles the encoding :)
