### ISSUE TITLE
Login to Facebook does not work

### ISSUE THREAD

**Issue by apfelpfluecker** [strohne/Facepager#211]
I use Facepager on Zorin OS (Linux) with wine, so I use the current Windows-version (Facepager 4.5).

When I try to log in to Facebook I get this error message (in the login popup):
> Fehler beim Zugriff auf die App
Leider wurde die App, die du verwenden willst, deaktiviert oder sie existiert nicht.

It also didn't work for a fellow student, who uses Windows 11.

![Bildschirmfoto vom 2024-06-21 13-02-49](https://github.com/strohne/Facepager/assets/65493517/0e034473-d6b2-43e5-9966-f2e1ca7e3374)

**Comment by catwolfman** [comment]
Dear @apfelpfluecker, unfortunately the Facebook access is currently restricted. We are aiding Facebook's app review team as best as we can right now to regain access and published a statement in our [Facepager User Group](https://www.facebook.com/groups/facepagerusers) on Facebook about this on Wednesday. Join the group for an update if and when the access will be restored in the coming days. [lh]

**Comment by strohne** [comment]
Back again, thanks for you patience :)
