### ISSUE TITLE
BadStatusLine after every N request

### ISSUE THREAD

**Issue by dorvak** [strohne/Facepager#25]
I'm still getting a BadStatus-Line Error on Win 7 (need to check this on my Mac). This error ocurrs after issuing a new request (f.e. this does not ocurr while paginating through the results). 

`HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/application/rate_limit_status.json?resources= blablabla (Caused by <class 'httplib.BadStatusLine'>: '')

An educated guess without debugging anything: 1) Some remainings of the old request inside the HTTPSConnection Pool (this seems to be a known request-bug with older version). 2) Some issues with proxies(network at the university (although this should not cause such error  3) Our threading-implementation breaks the ConnectionPool somehow

This is not really urgent, but quite annoying. I'll debug that in May (holidays!)

**Comment by strohne** [comment]
did't get this error for a long time now, i close the issue.
