### ISSUE TITLE
Read_Stream Permission in OAuth Dialog

### ISSUE THREAD

**Issue by dorvak** [strohne/Facepager#28]
Some Facebook-Pages require the users "read_stream" permission to access it's public feed. We should include this permission (as a standard or optional) in the OAuth dialog, otherwise users need to obtain it manually via the Graph-Explorer, f.e. https://developers.facebook.com/tools/explorer/109906609107292/?method=GET&path=me%3Ffields%3Did%2Cname&version=v2.0

**Comment by strohne** [comment]
This one was easy, needs testing...

**Comment by strohne** [comment]
Solved. If you need more permissions, create an own Facebook app and use these credentials.
