### ISSUE TITLE
API v2.0 Migration Facebook

### ISSUE THREAD

**Issue by dorvak** [strohne/Facepager#29]
For the future, we should think about making the v2.0 API as a standard endpoint (basically adding the /v2.0/ to the URL-Path, maybe update some preferences)

**Comment by strohne** [comment]
changed base path. everything looks fine. 

presets need to be tested and integrated help (including suggestion of endpoints, params and values) needs revision now. example: search for posts is depricated by now.

**Comment by dorvak** [comment]
Top, die Hilfetexte und Co. Können wir mal beizeiten anpassen bzw. Neu crawlen
