### ISSUE TITLE
Facebook Log In Window Is empty, and give errors 

### ISSUE THREAD

**Issue by precise-nizamuddin** [strohne/Facepager#34]
When i follow all steps and click in Facebook Log In button, i get an empty window , and get an error.
Can you explain where am i doing mistake ?
![facepager](https://cloud.githubusercontent.com/assets/7149479/7548601/adb07eae-f642-11e4-990c-b90316e07bb5.png)

**Comment by strohne** [comment]
I guess it is a problem with OpenSSL, not your mistake. Which version of Facepager did you use? Maybe try with another version?
