### ISSUE TITLE
GET statuses/show/<id> not formulated correctly

### ISSUE THREAD

**Issue by dimitrakopoulou** [strohne/Facepager#36]
Hi all,
Thank you for this great tool. At the moment, we are using Facepager to get individual Tweets by status id. We have noticed that the API call GET statuses/show/<id> is not formulated correctly having an extra slash between show and .json.
`https://api.twitter.com/1.1/statuses/show/.json?id=xxxxxxxxxxx`
The issues seems to be in “apimodules.py" line 623 in `options["query"]`
Thank you for resolving this. 
Dimitra

**Comment by strohne** [comment]
Thanks for your message.Unfortunately I can not reproduce this behavior, at least not in the master branch. As I read the documentation the canonical way to retrieve individual tweets by id would be: 

`https://api.twitter.com/1.1/statuses/show/xxxxxxxxxxx.json`

This works with Facepager by setting Resource to `statuses/show/<id>` and parameter `id` to `<Object ID>`.

Your way to formulate the request should be perfectly well being achieved by setting Resource to `statuses/show.json?id=<id>` and parameter `id` to `<Object ID>`.

Maybe it has been an issue in former versions, as the binaries are not always up to date?

**Comment by dorvak** [comment]
Did this solve the issue?
