### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by veenassit** [strohne/Facepager#37]
1. how to set two nodes with different resource and at the same time with different time stamp have to set the timer.

2. how to over write sql lite db, every time if my timer trigger whatever the data is presented in the view entire data available in database which is duplicate because facepager giving everytime full data(page information)

3. page information like paging, likes , comments all these information in database its storing as a single column as responses. but in the facepager view i can view in different columns. so how to set the same columns in sqllite db.

**Comment by strohne** [comment]
1. To your first question regarding the timer: the timing function by now is very rudamentery. I would start two instances of Facepager to achieve this.

2.To your second question regarding updating instead of inserting data: this is feature not a bug ;) Facepager keeps every data collected in the past, this is crucial for retracing the data collection process in the context of scientific research. Getting the needed data out of all data is not part of Facepager but of your data analysis process

3. All data is json encoded in sqllite db. As the schema of data e.g. may vary between different services we need a schemaless design here. Just decode the data or use the export function of Facepager.

**Comment by veenassit** [comment]
how to use it in linux environment.Can you help out with any doc or video if available.

**Comment by veenassit** [comment]
Hi,

Can you send any use-full link how to use facepager in linux.

Thanks,
veena

On Mon, Sep 21, 2015 at 11:55 AM, strohne <notifications@github.com> wrote:

> Closed #37 <https://github.com/strohne/Facepager/issues/37>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strohne/Facepager/issues/37#event-414431706>.
>



-- 
Thanks&Regards
G.Veena

**Comment by veenassit** [comment]
and how to automate this job trigger.

**Comment by strohne** [comment]
See src/readme.txt for hints how to use under linux.

If you need more advanced timer functions / job triggers you need to code it by your own. We would be glad if you did and shared the results.

Have fun.

**Comment by veenassit** [comment]
:)

**Comment by veenassit** [comment]
Hi,

need a help how to use facepager  in linux

1. downloaded tar file Facepager3-6-Linux86-64.tar and extracted
2. created credentials.py(here i mentioned fb access token)

how to execute/trigger  facepager? what is the command and how will provide
resource to the command? and  where data will be stored like in windows
environment sqllite db?

thanks in advance.

On Mon, Sep 21, 2015 at 12:26 PM, strohne <notifications@github.com> wrote:

> See src/readme.txt for hints how to use under linux.
>
> If you need more advanced timer functions / job triggers you need to code
> it by your own. We would be glad if you did and shared the results.
>
> Have fun.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strohne/Facepager/issues/37#issuecomment-141894141>.
>



-- 
Thanks&Regards
G.Veena

**Comment by dorvak** [comment]
Please see [this link}(https://github.com/strohne/Facepager/commit/b86d22f83550f6017de36768bef723cca538479b) for a basic description to build Facepager in Linux. 

You can start Facepager with "python Facepager.py" or create an executable file (or include a shebang-line and make it executable)

Regarding the storage: Yes, everything is stored in a sqlite-database, regardless of the OS.
