### ISSUE TITLE
Extract Reviews from Facebook Page

### ISSUE THREAD

**Issue by alvin1234** [strohne/Facepager#39]
I would like to get some reviews from a public Facebook page. However, when I try 
< application >/reviews in Resource, it returns error. I'm not sure if there is a problem with the code of Facepager or if I do not choose correct value in the drop down menu of "Resource". I'm grateful for your help.

![facepager_error](https://cloud.githubusercontent.com/assets/17779040/13697040/b59ebd60-e7a5-11e5-9f6a-a0e8befd5f32.png)

**Comment by strohne** [comment]
Hi, what is the error message and code? See offcut-node pls.

**Comment by strohne** [comment]
Maybe there is no edge called "reviews" anymore? Pls see Facebook API reference: https://developers.facebook.com/docs/graph-api/reference/v2.2/application/

**Comment by alvin1234** [comment]
Hi Strohne,

The error message is as below:

{
    "error": {
        "message": "Unknown path components: /reviews",
        "code": "2500",
        "type": "OAuthException",
        "fbtrace_id": "Ek/QaNoHnuS"
    }
}

I'm wondering if there is something wrong with the code related to
<application>/reviews.

Regards,
Alvin

**Comment by strohne** [comment]
Hi Alvin.

yes, there is no edge "reviews" anymore. Don't know how to get reviews by now. You should read the Facebook API reference for alternatives.

strohne

**Comment by alvin1234** [comment]
Hi Strohne,

Thank you very much for your reply!

Regards,
Alvin
