### ISSUE TITLE
CSV structure occasionally broke

### ISSUE THREAD

**Issue by nikicc** [strohne/Facepager#40]
Some FB posts cause exporting to CSV to break. By break I mean that each post is not in its own line any more since some posts are broken over multiple lines. For example, this is printscreen of a post online (coming from [here](https://www.facebook.com/Piratska.Stranka.Slovenije), scroll down to 23rd May 2014)
<img width="421" alt="screen shot 2016-06-01 at 21 22 06" src="https://cloud.githubusercontent.com/assets/713026/15722627/f2351560-283e-11e6-948c-d43fa21d307b.png">

The resulting CSV is broken into multiple lines like this:
```
"594";"4";"1";"98358327274_10152537848242275";"data";"fetched (200)";"2016-06-01 21:07:13.278147";"Facebook:<Object ID>/posts";"PIRATSKA STRANKA SLOVENIJE";"Posnetek včerajšnjega TV soočenja na RTV1 na katerem smo sodelovali tudi mi in na katerem je bil naš kandidat, po mnenju mnogih, nesporni zmagovalec.

Prepričajte se sami. Priporočamo tudi ogled včerajšnje aktivnosti na twitterju pod hashtagom #EUVolitve
https://twitter.com/search?q=%23euvolitve
";"51";"6";"13";"2014-05-23T07:34:08+0000"
```

This prevents Excell to import the data correctly. Maybe we should escape newlines from messages when exporting to CSV?

**Comment by strohne** [comment]
interesting issue. i have no problem with line breaks when opening the file with double click. the line breaks break indeed when opening from inside excel.

in future version we should have an export option to delete line breaks.

workaround until then: a) open with double click or b) open in texteditor and replace all line breaks not preceded by a quotation mark

**Comment by nikicc** [comment]
No worries, I already fixed it in Python. I just wanted to give a heads-up about the issue. 

Also, thanks for a prompt reply and it's great to hear this will be fixed in a future version!

**Comment by strohne** [comment]
thanks for commenting. maybe you could create a pull request?

**Comment by nikicc** [comment]
I can try if I'll find some time to set the environment up 😄
