### ISSUE TITLE
Installation package for MAC for latest commits

### ISSUE THREAD

**Issue by marcusnjr** [strohne/Facepager#42]
Hello guys! Thanks for creating Facepager! Awesome application. May I know if the Mac installation package with the recent commit of fixing the export text line break will be out anytime soon? Thanks.

**Comment by dorvak** [comment]
I´m working on it right now & keep you posted as soon as the version is compiled

**Comment by dorvak** [comment]
Edit: Unfortunately, this will take a while. Creating binaries on a Mac is a huge mess. As a side-note: Mac Versions will only run within the same OSX-Version (10.11.5; or newer ones)

**Comment by dorvak** [comment]
Hey, you might try that version: https://www.dropbox.com/s/c6sj53gab1n3bi5/Facepager.app.zip?dl=0  (unzip beforehand)

**Comment by marcusnjr** [comment]
Thanks guys!

**Comment by dorvak** [comment]
@marcusnjr Did this version work for you & can i close this issue?

**Comment by marcusnjr** [comment]
@dorvak yes it works like charm. Thanks for the help. You can close the issue. 👍
