### ISSUE TITLE
How to get emails of facebook pages fans?

### ISSUE THREAD

**Issue by kamov** [strohne/Facepager#44]
How to get emails of facebook pages fans?
thanks

**Comment by strohne** [comment]
I don't know if this is possible, pls read the Facebook Graph API Reference.

**Comment by kamov** [comment]
I read and seem not possible.
I guess if someone has find a solution for this.

Since facebook have a redirect email username@facebook.com
I think that if we get username of facebook fan page, we can also get email.

For get username how to do ? 

I try <page>/members but not work

**Comment by strohne** [comment]
members is no valid edge of page objects, see Facebook Graph API reference

I think it is not possible, see http://stackoverflow.com/questions/4018849/facebook-api-get-fans-of-people-who-like-a-page
