### ISSUE TITLE
Dropdown of Resource not listing for choose options.

### ISSUE THREAD

**Issue by nguyenducphu** [strohne/Facepager#45]
Dropdown of Resource not listing for choose options.
See link for screenshot: https://dl.dropboxusercontent.com/u/6552771/facepager.png

Please fix :)

I'm using MacOS Sierra 10.12

**Comment by strohne** [comment]
i am not sure whether i get the point:
options are implemented for "<post>" not "<posts>", please try.

**Comment by dorvak** [comment]
The dropdown doesn`t seem to work on OS X, I`ll check this soon.

**Comment by strohne** [comment]
Maybe the doc is not loaded, needs os specific path handling? See https://github.com/strohne/Facepager/blob/master/src/apimodules.py#L151

**Comment by strohne** [comment]
should be fixed in version 3.9
