### ISSUE TITLE
YouTube Comments Download

### ISSUE THREAD

**Issue by Bawage** [strohne/Facepager#50]
Hi Guys,

I am trying to get the comments from youtube by using this tutorial "http://tillkeyling.com/facepager-and-the-youtube-api-v3-a-quick-tutorial.html#facepager-and-the-youtube-api-v3-a-quick-tutorial".
However, I am getting the following error. I have tried everything that I can. If anyone can help me it would be much appreciated.
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "keyInvalid",
    "message": "Bad Request"
   }
  ],
  "code": 400,
  "message": "Bad Request"
 }
}

**Comment by strohne** [comment]
Just checked the tutorial, works for me. Please give some more details about what you are doing: 

1. What are your settings in Facepager? 
2. What is in the status log (make sure to cross out the api key)?
3. What are the settings of your developer account - where did you get it? MAybe you could post a screenshot (again, make sure to cross out any credentials and personal information)

**Comment by Bawage** [comment]
**Facepager Settings**
URL Path: https://www.googleapis.com/youtube/v3/commentThreads?
Parameters:
part --> snippet
videoId --> <Object ID>
Key --> "empty"
key to extract --> items
key for ObjectID --> id

**Status Log:**
2017-03-20 15:41:12.873000 Fetching data for a from https://www.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=a&key=

**YouTube Key**
I got the key from google developer
see the screen short
![fp](https://cloud.githubusercontent.com/assets/25748267/24088991/55d281b2-0d85-11e7-9c19-cc0ae9b889f7.PNG)

**Comment by strohne** [comment]
Looks like wrong settings / nodes to me:

- "a" is not a valid ID of a video
- key (lowercase!) has to be set to you api key, not "empty"
