### ISSUE TITLE
Twitter Stream Disconnecting/Crashing 

### ISSUE THREAD

**Issue by Bawage** [strohne/Facepager#51]
Hi,
I am trying to collect tweets, but my stream is disconnecting again and again. I am getting the following message in status log: 
2017-03-20 15:36:15.476000 Exception: IncompleteRead(0 bytes read, 2 more expected).

Did not change any setting. It was working fine two days ago (last time I used)! Max Tweets that I can get are 300-700.

**Comment by strohne** [comment]
Which Twitter-module (there are two)? Which settings?
