### ISSUE TITLE
Collecting data from Facebook groups: Errors 400 and "Exception: global name 'sleep' is not defined"

### ISSUE THREAD

**Issue by phoebechua** [strohne/Facepager#52]
Hello, 

I'm currently trying to use Facepager to collect data from a Facebook group. 

Let's say that the Facebook URL is https://www.facebook.com/groups/1420997938186432/.

I wasn't sure how I should've input the node, and so I tried doing that in two ways. 

(1) When I used the node:  groups/1420997938186432/, I received the error (400).
(2) When I used the node:  1420997938186432/, I received the error: "Exception: global name 'sleep' is not defined."

How can I go about extracting information from Facebook groups? Am I incorrectly setting up the variables in Facepager? Here's the link to the screenshot of my settings in Facepager: [https://drive.google.com/file/d/0BzGweDhxb-SjaE90RUNzX0FhNkE/view?usp=sharing](url) 

Thanks in advance for your kind assistance.

Best, 
Phoebe

**Comment by strohne** [comment]
Just a quick note regarding
> "Exception: global name 'sleep' is not defined."
This is a bug in Facepager, just hit the Fetch data-button again. Does it work?

(Nodes should be inserted without slashes or url parts, just the ID, your screenshot looks ok.)

**Comment by phoebechua** [comment]
Thanks for your quick response! 

Your suggestion worked. I'm now trying to extract data from a closed Facebook group that I have access to (I've joined the group.) The group ID is 351783714851597 and the URL is https://www.facebook.com/groups/351783714851597/. 

The following is a screenshot of my interface of Facepager: 
![image](https://cloud.githubusercontent.com/assets/13762980/24130925/caf40b1e-0da8-11e7-9bfb-49f15edc84c7.png)

and this is the resulting collected data: 
![image](https://cloud.githubusercontent.com/assets/13762980/24130958/eeac11a0-0da8-11e7-9f3b-2e39c58863d7.png)

I'm unfortunately unable to correctly collect the data. Is it because my node level and parallel thread is incorrect (I'm not sure what the appropriate setting is to begin with.)?

Thank you again for your help!

Best, 
Phoebe

**Comment by strohne** [comment]
That should work, settings are ok (see Help-button for further information).

Did you expand the node by clicking on the symbol left between the starting node? 

And are you able to collect 'profile' information about the group (remove "/feed" from the resource field)?

**Comment by Gemmahhh** [comment]
Hi. Please how did you get the access token. I've tried getting data from Facebook but it keeps giving me 'error 400'

**Comment by strohne** [comment]
Collecting data from groups is not possible anymore with the preregistered Facebook-API-access. If you have further questions regarding how to use Facepager, please ask in the Facebook User Group. (GitHub is the place for development issues). :)
