### ISSUE TITLE
Object empty

### ISSUE THREAD

**Issue by FernandoJackMedeiros** [strohne/Facepager#53]
Hi!
I'm very excited about discovering Facepager, but life is not a bed of roses.. 

I need extract Fb IDs of my friends. When I try it, the result is an object "empty".

I've already tried:
- using "me" node
- using fb ID as <user>
- using fb ID as <Object ID>
...

I just can fetch the basic info of my ID, using <Object ID> in "Resources" box without parameters, but that's all. I can not fetch any data from this, like friends, events, etc, etc. The try always results in Object empty.

**Comment by strohne** [comment]
Please be a little bit more precise: which settings did you try for example with the "me" node? 

To get related data please have a look at the Facebook Graph API reference, there may be privacy restrictions.

Collecting user related data often is restricted by privacy settings. Maybe you should register your own Facebook App with the relevant permissions and use it with Facepager (fields "client id", and "scope").

**Comment by FernandoJackMedeiros** [comment]
I've noticed that the ID used is the scoped app ID, not the facebook "unique" ID, but, even with my fb ID, it did not work.

As you see in the atachment, I have tried in several ways.. with "me", with fb ID, calling <Object ID>, <user>, etc.. I can not fetch any information..

In case I register a Facebook App, is there a specific config that I need? 
client ID and Scope are that fields given by the facebook app, right?

even though this, if I want to fetch data from other profiles, I will have to create an own facebook App for each one of them?

![facepager](https://cloud.githubusercontent.com/assets/26741183/24408392/002142ba-13a4-11e7-9748-038e9a82e56b.PNG)

**Comment by strohne** [comment]
I guess this is restricted due to privacy settings, no way, see http://stackoverflow.com/questions/23850807/get-all-user-friends-using-facebook-graph-api-android

For using your own app see https://github.com/strohne/Facepager/blob/master/src/credentials.py.readme

**Comment by strohne** [comment]
Well, I don't understand the problem. You want to get the IDs of your Facebook friends. And you got the IDs. What is missing?
