### ISSUE TITLE
fan_count

### ISSUE THREAD

**Issue by world33** [strohne/Facepager#54]
Is there any way to use Facepager to retrieve just a Facebook page total count of likes and followers?
For example for this Facebook page it would be
https://www.facebook.com/Harvard/
**4,938,347** people like this (total fan count)
**4,862,079** people follow this

I could not find any preset to do so.
The total fan count (fan_count) is referenced in the graph api at the following page:
https://developers.facebook.com/docs/graph-api/reference/page/

**Comment by strohne** [comment]
Yes, it is possible. But Facepager is not an one-click-application. You need to study the settings and get familiar with the way the Facebook Graph API works by yourself, sorry.

Look at the Help-Page, try the Getting Started (which will show you how to get like count), play around with settings...

**Comment by world33** [comment]
Thanks for your reply. I found the solution.
I could not find any email where to share the Jason file as per your help page suggestion.
Below the Jason code if interested in adding it to the default presets:

{
  "columns": [
    "name",
    "message",
    "type",
    "metadata.type",
    "talking_about_count",
    "likes",
    "likes.count",
    "shares.count",
    "comments.count",
    "created_time",
    "updated_time",
    "category",
    "category_list",
    "id"
  ],
  "options": {
    "params": {
      "<page>": "<Object ID>"
    },
    "relation": "/<page>/?fields=fan_count",
    "pages": 1
  },
  "name": "Get Page Fan Count",
  "module": "Facebook",
  "description": "Get the total number of likes of a Facebook Page (fan_count)"
}

**Comment by strohne** [comment]
Great, thank you, I will add it in the next release.

**Comment by world33** [comment]
No worries, I edited it lately at GitHub and removed unnecessary table fields.
