### ISSUE TITLE
Export data - switching from CSV to Tab

### ISSUE THREAD

**Issue by world33** [strohne/Facepager#55]
I have added this preset retrieving multiple Page information including:
**id
link
category
about
company_overview
description
general_info
impressum
mission
affiliation
contact_address
location
phone
emails
website
founded
featured_video
start_info
can_post
verification_status
app_links
press_contact
picture**

The Jason file is:
``{
  "columns": [
    "id",
    "link",
    "category",
    "about",
    "company_overview",
    "description",
    "general_info",
    "impressum",
    "mission",
    "affiliation",
    "contact_address",
    "location",
    "phone",
    "emails",
    "website",
    "founded",
    "featured_video",
    "start_info",
    "can_post",
    "verification_status",
    "app_links",
    "press_contact",
    "picture",
      ],
  "options": {
    "params": {
      "<page>": "<Object ID>"
    },
    "relation": "<page>?fields=id,link,category,about,company_overview,description,general_info,impressum,mission,affiliation,contact_address,location,phone,emails,website,founded,featured_video,start_info,can_post,verification_status,app_links,press_contact,picture",
    "pages": 1
  },
  "name": "Get Page Info",
  "module": "Facebook",
  "description": "This preset retrieves the following items (if available and published):\n\nid\nlink\ncategory\nabout\ncompany_overview\ndescription\ngeneral_info\nimpressum\nmission\naffiliation\ncontact_address\nlocation\nphone\nemails\nwebsite\nfounded\nfeatured_video\nstart_info\ncan_post\nverification_status\napp_links\npress_contact\npicture"
}``

When exporting into a CSV file and opening it with excel all commas included in the retrieved fields with text containing commas alter the final outcome of the excel file and present the data in a messy way with fields truncated wherever there is a comma:
![screenshot](https://cloud.githubusercontent.com/assets/20501877/25031499/b24b59fc-2110-11e7-8583-032455d7d17a.png)

Would it be possible to switch to or add Tab Delimited as an alternative option to export the data?
It is very rare to find tabs in descriptions and text fields that might mess up with the importation or opening of the file in Excel.

**Comment by strohne** [comment]
I guess this is not a Facepager problem. Try the text import wizard of excel.

We will provide an option for tab delimited files in the future. But this is just for convenience, export should work by now without problems.

btw: your way to specify parameters is complicated. You can put these in a parameter field (left side = key; right side = value).

btw: it looks like you have set the base path to version 2.5 or higher. with version 2.2. you don't need to specify every single field

**Comment by strohne** [comment]
Added option to select sparator in latest release, see https://github.com/strohne/Facepager/releases/tag/v3.8.0

**Comment by world33** [comment]
Thank you
