### ISSUE TITLE
version 3.5 / likes.count, comment.count are blank

### ISSUE THREAD

**Issue by rutujabodhe** [strohne/Facepager#57]
I was trying to extract posts, comment_count and likes_count.
It is extracting posts but like.count, comment.count, shares.count are not working.
if instead i select likes.data.name it is showing the names of whoever has liked the post.
so how can i find out counts ????
i m using macbook air

**Comment by strohne** [comment]
Pls work through the help file, look at the presets and get familiar with the Facebook Graph API reference. Facepager is no one-click-is-all-you-need-application.

If you need more help pls be specific about what you did, what you expected and what you got (settings etc.)
