### ISSUE TITLE
Wikipedia preset not loaded, version 3.8

### ISSUE THREAD

**Issue by world33** [strohne/Facepager#59]
Hi,

When I try to apply the Scrape Wikipedia List of museums Preset it does not seem to load.
I am not sure if this is the only preset that does not load. I have not tested them all

Cheers

**Comment by strohne** [comment]
This was an experimental preset (see scrape branch) not intended to be deployed. I will remove it in the next release and update the preset folder.

**Comment by strohne** [comment]
should be removed in the latest release
