### ISSUE TITLE
Size of Comments & Likes

### ISSUE THREAD

**Issue by togarg** [strohne/Facepager#61]
Hi, The count of Comments & Likes is not working. 
Is there a way we can add the basic functionality of Size, Length to the the preset? 

Also, the replies to comments are not getting captured. Any idea how we can incorporate that?

**Comment by strohne** [comment]
Thx, fixed it. Workaround until next release: replace `from.name` with `from{name}` in the fields-parameter.

To get replies fetch comments of comments, see Facebook Graph API reference for further information.
