### ISSUE TITLE
facepager: Can't find my access token

### ISSUE THREAD

**Issue by aritra1994** [strohne/Facepager#62]
I am a new user of facepager and I wanted to crawl public data from facebook for my thesis work. But I cant fetch data because of missing access token. I have tried "login to Facebook" button. It shows Success but my access token bar is still empty. How ca I get my access token??

**Comment by strohne** [comment]
The login-button is the way to go; acces token field should be filled with stars or points (like password fields on websites). Which version of Facepager / which OS do you use?

**Comment by aritra1994** [comment]
I am using win-10 and the version is 3.5. I have also tried 3.6 but facing same problem.

**Comment by aritra1994** [comment]
![capture](https://cloud.githubusercontent.com/assets/20509265/26751125/de2240e4-4853-11e7-8107-f162b759d84e.JPG)

**Comment by strohne** [comment]
Both versions are outdated. Please switch to newest version 3.8.2 (see [releases page](https://github.com/strohne/Facepager/releases))

**Comment by aritra1994** [comment]
Still nothing happened.

**Comment by aritra1994** [comment]
![capture](https://cloud.githubusercontent.com/assets/20509265/26753782/da704554-488f-11e7-9e82-7fbee205c6f4.JPG)

**Comment by aritra1994** [comment]
![capture2](https://cloud.githubusercontent.com/assets/20509265/26753784/e54875aa-488f-11e7-98bb-53cfc4b2ee9a.JPG)

**Comment by strohne** [comment]
Well, actually I have no idea. Could you please look into the Facepager-Folder below your users-folder (e.g. `C:\Users\<yourusername>\Facepager`) ... are there any log-files?

BTW: change version in basepath to at least v2.3 (v2.2 is depricated by now, I forgot to update the default setting).

**Comment by aritra1994** [comment]
Yes there is a log file. And I have changed the default graph api version.
Is it possible to extract data from my friends wall by facepager ?

**Comment by strohne** [comment]
Then it works now? What is in the log file?

Regarding data from friends wall: yes (in principle) and no (not easy). You need to setup your own Facebook App and use this with Facepager. Your friend needs to approve the app. See https://developers.facebook.com/docs/graph-api/reference/v2.9/user/feed

**Comment by aritra1994** [comment]
yes its working now. Thanks a lot.
How to connect my Facebook app with Facepager? Can you provide me any doc in this regard?

**Comment by strohne** [comment]
Great.

You need to enter the client id into the field on the Facebook tab and then login.

See https://github.com/strohne/Facepager/blob/master/src/credentials.py.readme for how to get the client id.

**Comment by dkxmen** [comment]
Hi, so do you delete the log file or waht do you do? 

This is what is in the log file:
"
2021-01-12 20:50:20,387 ERROR:Access key or secret key is missing, please fill the input fields!
NoneType: None
2021-01-12 20:50:21,678 ERROR:Access key or secret key is missing, please fill the input fields!
NoneType: None
2021-01-12 20:50:22,328 ERROR:Access key or secret key is missing, please fill the input fields!
NoneType: None
"

**Comment by strohne** [comment]
Hi @dkxmen , I don't see how this is related to developing Facepager? If you have questions with regard to using Facepager, please try out the Facepager user group on Facebook :)
