### ISSUE TITLE
Problem when I try to collect reactions

### ISSUE THREAD

**Issue by vriccobono** [strohne/Facepager#63]
First, I would like to thank you for your amazing application. 

It's really handy but I have some issues when I try to collect the reactions of the posts...I managed to collect the likes of the posts in which I'm interested by adding summary.total_count in the column section. But it only gives me the "like" reactions and not the sum of all the reactions. 

I tried to search a solution on the web and I tried some combinations after reading the Facebook api documentation but I'm stuck with this issue.

I would be grateful if you could help me.

**Comment by strohne** [comment]
Well, it works for me with `<Object ID>/reactions`, see https://developers.facebook.com/docs/graph-api/reference/v2.9/post/reactions

Take care to set the version in the basebath to v2.6 at minimum.

Could you post a screenshot or the settings you tried?

**Comment by vriccobono** [comment]
Thank you very much for your help, I'm new to this kind of tools. Here is a screenshot of the settings I tried. 
![image](https://user-images.githubusercontent.com/25531276/27005547-a6224aea-4e20-11e7-821e-b069d4206fdd.png)

What I would like to have is the total number of reactions per post. Until now, I could only manage to get the total "like" per post by selecting the column "summary.total_count".

**Comment by vriccobono** [comment]
Never mind I managed to obtain what I wanted thanks to your previous answer :-) 
Thank you very much for your time! 
![image](https://user-images.githubusercontent.com/25531276/27005628-81ce9e4e-4e22-11e7-85f6-7ae7243aedb4.png)

**Comment by vriccobono** [comment]
I am sorry to bother you again but now that I can get the reactions and the likes, I am not able to obtain the count of the other reactions. Here I tried with the "love" one. Do you know where I can find the correct ID ? I tried to put it in capital letters just like on the page you shared but It does not work. 

![image](https://user-images.githubusercontent.com/25531276/27005876-9571ce44-4e27-11e7-8636-31da141ee550.png)

**Comment by dorvak** [comment]
This is an API issue (probably a wrong endpoint, as there is no endpoint /LOVE), please see the API documentation https://developers.facebook.com/docs/graph-api/reference/post/reactions

We will not answer API-specific questions anymore.
