### ISSUE TITLE
Extracting facebook group data - Error 400

### ISSUE THREAD

**Issue by PolinaWeb** [strohne/Facepager#66]
I saw that Phoebechua had posted a similar problem a while ago, but I'm not sure about the resolution of the issue. 
I'm currently trying to extract the feed of a secret facebook group, of which I am a member. 
Every time I try, I receive an error message (400)
I tried to match my settings to the one shown in the posts by phoebechua and I saw in another thread that it might help to update the base path to v2.3.
Extracting data from regular facebook pages seems to work just fine, but I can't get it to work with facebook groups. 

I'd be super thankful for any hints as to where I am going wrong. Attached is a screenshot of my settings and the error message.

Thank you!

![facepager_screenshot](https://user-images.githubusercontent.com/29864702/27795139-348b4340-6005-11e7-890b-c9be4bf1b74a.JPG)

**Comment by strohne** [comment]
Well, what is the error message (see offcut node)?

**Comment by PolinaWeb** [comment]
Oh, sorry!
New screenshot is attached. Unsupported get request. 
I'm quite sure that the ID is correct, so maybe the problem is with the privacy settings of the group? I found the screenshotted paragraph in the graph api documentation - as the group is non-public, maybe a "simple" membership is not sufficient?

Thank you!

![error_facepager](https://user-images.githubusercontent.com/29864702/27798115-61e99304-6010-11e7-8dc4-b243eadc1e82.JPG)
![facebook graph api](https://user-images.githubusercontent.com/29864702/27798128-6c5ccd24-6010-11e7-9189-e7a9732459e7.JPG)

**Comment by strohne** [comment]
Yes, afaik simple membership is not enough for closed groups. This results in "Unsupported Get Request"-errors. I am not sure whether admins can collect data via API. I will try it out in one of my groups later.

**Comment by strohne** [comment]
Just tested it: I have access to the group feed only for a group where I am admin.
