### ISSUE TITLE
Question on the tool

### ISSUE THREAD

**Issue by mingtam** [strohne/Facepager#67]
Hi,

I would like to extract all the values from my facebook search like below:
https://www.facebook.com/search/str/81%25E2%2581%25842%2Botto%2Be%2Bmezzo%2Bbombana/stories-keyword/stories-public?see_more_ref=eyJzaWQiOiIiLCJyZWYiOiJoZWFkZXJfc2VlX2FsbCJ9

eyJlc2lkIjoiUzpfSTEyNjQ4OTMxNDU6MTAyMTM1MTM1NTExMzQyMjIiLCJwc2lkIjp7IjEyNjQ4OTMxNDU6MTAyMTM1MTM1NTExMzQyMjIiOiJVenBmU1RFeU5qUTRPVE14TkRVNk1UQXlNVE0xTVRNMU5URXhNelF5TWpJPSIsIjEwMDAwNjYzMzQ5OTQ1NjoyMDExMzQ2NjAyNDI5NzcwIjoiVXpwZlNURXdNREF3TmpZek16UTVPVFExTmpveU1ERXhNelEyTmpBeU5ESTVOemN3In0sImNyY3QiOiJ0ZXh0IiwiY3NpZCI6IjQ1NGFlNGM4NDNjY2I1ZTc1NjRkNDljMmM2ZTQ0MzE4In0

one of the posts I clicked and it has the value esd = " ... " 

can I use this application to get those values?

**Comment by strohne** [comment]
Well, did you try it? Pls work through the getting started of Facepager and read the Facebook Graph API documentation: https://developers.facebook.com/docs/graph-api/using-graph-api/ (scroll down to "searching"). I am not sure, whether it is possible, it depends.
