### ISSUE TITLE
Can't fetch likes anymore

### ISSUE THREAD

**Issue by welterrr** [strohne/Facepager#69]
Hi,
i need help :) 
I dont know why but i just can not fetch the likes_count, talking_about_count or any other infos of a fanpage. The only things i can fetch are the name, the id and the pages liked by the page.

Do you know what's going on, are you facing similar problems or do you know what I am doing wrong? A few months ago it was working great :(

Thanks for your help 

<img width="1279" alt="bildschirmfoto 2017-08-24 um 22 46 05" src="https://user-images.githubusercontent.com/31324465/29687875-29034d6e-891e-11e7-9a4e-0ea9fe335cda.png">

**Comment by strohne** [comment]
There have been some API upgrades by Facebook. API version 2.3 is no 
longer supported and automatically redirected to some higher version. 
Facebook now only provides limited fields by default, see 
https://developers.facebook.com/docs/graph-api/using-graph-api#fields

Change the version in the base path to `v2.10` and use the 
`fields`-parameter (left side) to specify the data you want (right side, 
comma delimited). The available fields are listed in the Facebook Graph 
API reference, e.g. 
https://developers.facebook.com/docs/graph-api/reference/page/

BTW: you are using the latest developer version which has not been 
released yet. This is fine but most of the presets are not updated yet. 
If you like you can support us by creating some basic presets and 
sending them to me.

**Comment by welterrr** [comment]
Thank you for responding so fast. It's working now.

**Comment by mithils** [comment]
What would I change the Resource and parameters boxes to if I would like to pull my own Facebook data such as posts? ([https://developers.facebook.com/docs/graph-api/reference/v2.10/post/])

Note: I'm still on Facepager 3.7 as I have a Mac

**Comment by mithils** [comment]
[](https://developers.facebook.com/docs/graph-api/reference/v2.10/post/)

**Comment by strohne** [comment]
See the help (add "me" as node). And pls don't use existing issues for new questions.
