### ISSUE TITLE
Data Fetch Empty(macOS,Facepager 3.7)

### ISSUE THREAD

**Issue by mithils** [strohne/Facepager#70]
I understand that there is a switch in the new API and I have followed the directions on the readme as best as I could. I have read the API reference sheet and played around on Facebook's Graph API explorer to get a better understanding. On Graph API explorer, this URL gives me the desired output of all my posts and the associated comments and likes: https://graph.facebook.com/v2.10/me/posts?fields=comments,likes

From what I understood, I tried replicating the same results on FacePager with the following setup to get a similar URL, but no data is shown whatsoever. 
![image](https://user-images.githubusercontent.com/9203545/30306428-11b1cdda-9746-11e7-9529-8ba3dc0e131c.png)

I think I might be missing a small step, so any help is appreciated.

**Comment by strohne** [comment]
Everything looks ok but I think you need the user_posts permission. Pls try to insert "user_posts" in the scope field and relogin. See section about read permission in the reference: https://developers.facebook.com/docs/graph-api/reference/user/feed/

**Comment by welterrr** [comment]
Im not sure if this helps you, but I need to set the parameters <page> (in your case <user> i guess) and <Object ID> below the "fileds" and "comments, likes" sections.
Maybe thats the problem - hope you can figure it out
<img width="403" alt="bildschirmfoto 2017-09-12 um 18 22 40" src="https://user-images.githubusercontent.com/31324465/30337244-f50d71e6-97e7-11e7-8b25-09a84e8fba38.png">

**Comment by welterrr** [comment]
sorry - github seems not to display what i was trying to say... 
try writing "<user>" and "<Object ID>" in the parameter section below your "fields" and "comments, likes"

**Comment by welterrr** [comment]
Im not sure if this helps you but i need to set the parameters page (in your case user I guess) and Object ID in the section below the fileds and comments, likes.
I hope you can figure it out
<img width="403" alt="bildschirmfoto 2017-09-12 um 18 22 40" src="https://user-images.githubusercontent.com/31324465/30337445-9cb74d9a-97e8-11e7-89e1-379420c7dd2d.png">

**Comment by strohne** [comment]
I just created a group on Facebook for getting help: https://www.facebook.com/groups/136224396995428/

Please go to this group. We would like to reserve GitHub issues to real development issues in the future.
