### ISSUE TITLE
Need help with a preset

### ISSUE THREAD

**Issue by welterrr** [strohne/Facepager#71]
Hi guys,

I am looking for a preset and hope someone has experience with this. 

I want to fetch Fanpages and want to know how much of the Fans come from a certain country /current_location/hometown.

So i want to to get to know something like 
Eminem has 25% of his likes from Germany.

I know that i will never get the real numbers due to privacy settings, but maybe there is a way to find out a little at least.

Appreciate your help

best regards

**Comment by strohne** [comment]
This is a help request, not a bug or an development issue: Please ask your question in the Facepager User Group: https://www.facebook.com/groups/facepagerusers/
