### ISSUE TITLE
Text is clipped vertically in Data View - Windows 10 facepager 3.8.2

### ISSUE THREAD

**Issue by danpk1** [strohne/Facepager#73]
Hiya 
Will it be possible to repair the vertical spacing or whatever it is that is causing the text to be clipped in the data view window (Win10).  On my installation its unreadable because the bottom half of the text is missing. Perhaps I'm missing a setting somewhere (font related)? As per below

<img width="515" alt="clipped text" src="https://user-images.githubusercontent.com/33806474/32992449-d5065436-cd42-11e7-86a6-e0372e156e9f.png">

**Comment by strohne** [comment]
Interesting special effect. :) What is your screen resolution? And do you use the scaling feature of windows? (The row height is 17px by default.)

**Comment by danpk1** [comment]
I'm using 2560 x 1440 resolution and scaling 150%

TBH I did try to remove the scaling but this had no effect

**Comment by strohne** [comment]
I will try to fix it in the next days, may take a little while. In the meantime you could "Copy JSON to Clipboard" and paste it in a text editor (like Notepad++) as a workaround.

**Comment by danpk1** [comment]
Thanks for looking into  this, much appreciated. I can confirm it is perfectly usable and as you mention I have the option of copying to clipboard.

**Comment by strohne** [comment]
I think it is fixed in the new version 3.9. There is no release yet because some presets are still missing, but you can try the builds in the build-folder if you like.

**Comment by danpk1** [comment]
Hello there,

Thank you so much for your help. I can confirm all working in version 39.
