### ISSUE TITLE
trim parameters

### ISSUE THREAD

**Issue by alexgonca** [strohne/Facepager#76]
This is not an error but just a suggestion:
Two of my students had the same problem: they copy-pasted the "Base path" but, inadvertently, they also copied a space or a new line (\n) at the end of the string.
For that reason, Facepager was unable to fetch the data and it took them a while to find out that the white space was the problem.
I think Facepager could call Python's function strip (https://docs.python.org/3/library/stdtypes.html#str.strip) before it uses the parameters given by the user.

**Comment by strohne** [comment]
Thank you for the suggestion, good idea. I will check this in on of the next releases

**Comment by strohne** [comment]
Next release will have white space stripped: https://github.com/strohne/Facepager/commit/8989f6ab4c3197612df411bb111fd365e7376b62
