### ISSUE TITLE
Facepager cli

### ISSUE THREAD

**Issue by LeoCBS** [strohne/Facepager#80]
Hi, have some command line to interact with facepager?

**Comment by strohne** [comment]
Nice idea. We have not implemented this. And there are no plans to implement this because such things usually are out of scope for nonprogramming users.

Facepager is made with Python..feel free to add functionality. I would start with making actions in src/actions.py accessible.

**Comment by LeoCBS** [comment]
Nice strohne, i will look src/actions.py to understands more facepager code. i update this issue when i have more ideias about cli  API

**Comment by strohne** [comment]
I close this issue since we have no plans to develop this feature. If you have further contributions, pls let us know.
