### ISSUE TITLE
Empty cells when exporting

### ISSUE THREAD

**Issue by woopelaye** [strohne/Facepager#85]
When I fetch data (Twitter), all the information is fetched BUT when I export, some random cells appears to be empty (see screenshot)

It's weird because it really seems random and it makes it a bit useless. See screenshot. Thanks!

![image](https://user-images.githubusercontent.com/25085559/38382088-d4a8be5c-38d6-11e8-9ddc-e68b43719305.png)

![image](https://user-images.githubusercontent.com/25085559/38382131-f8be0946-38d6-11e8-9b04-afe3359ecd31.png)

**Comment by strohne** [comment]
Strange, I cannot reproduce this.  Could you please write down the exact steps to reproduce it? This would be of great help.

Looks like you used the "wide format" export option. Does this happen without this option, too?

**Comment by woopelaye** [comment]
Thanks for the quick answer, yes it does the same thing with the «Wide format» option

What I do is this:
![image](https://user-images.githubusercontent.com/25085559/38383246-ffabaa80-38d9-11e8-8995-00c7c1dad549.png)

Custom tables:
id
text
user.name
user.screen_name
user.description
user.location
lang
user.followers_count
user.friends_count
retweet_count
created_at


then I add a keyword as a Node, select the node than fetch data.

 
After that, I select the parent Node and click EXPORT with the following settings:
![image](https://user-images.githubusercontent.com/25085559/38383391-67a2790c-38da-11e8-883b-7971008da487.png)

Here is the result file (with some cleaned up columns)
https://docs.google.com/spreadsheets/d/1JQ7n_VlMfxztLrCecrrRVks1bSjEI6OU_XpzpUL1wu0/edit?usp=sharing

Hint: It does that only with twitter, I've tried some presets with FB and it export perfectly

**Comment by strohne** [comment]
Thank you for the details. I still can't reproduce this. Can you give me the exported csv-file (without modification)?

And did you try *not* to check the wide-format option?

**Comment by woopelaye** [comment]
Hello there. I found the problem and it's Google Spreadsheets fault. It fails to export CSV correctly. Tried with Open Office and it works like a charm!

You can close this 💃 and a big big thanks for your help. This piece of software is perfect

**Comment by strohne** [comment]
Thank you for the feedback, that helps a lot.
