### ISSUE TITLE
Facepager unable to fetch closed group data?

### ISSUE THREAD

**Issue by brianrutledge** [strohne/Facepager#86]
Hi,

I'm an admin of a large facebook group and another admin and I have decided to do some reasearch on the conversations being had in the group.

I've successfully downloaded and installed the latest facepager release 3.9 for OSX high sierra.
I used the button in facepager to log in to FB and was successful, but ran into issues with base path (which I then changed to read "https://graph.facebook.com/v2.12/") and the the access token generated was not working. I went directly to the graph.api site and got myself an access token and pasted that into facepager. SUCCESS!
The program appears to be functioning normally, and I was able to fetch a whole bunch of data from my own personal page.

However, when I enter in the closed group page id# as a new node and run a query for <group> (or for virtually anything else) I just get back errors. 

Specifically error 400 and then 
"{
    "error": {
        "message": "Unsupported get request. Object with ID '450170501807970' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api", 
        "code": "100", 
        "type": "GraphMethodException", 
        "fbtrace_id": "DF1gUhBFjqa", 
        "error_subcode": "33"
    }
}"

I've tried creating a node with "groups/ExplainingPainScience/" and with "45017050180797" and both return me nothing but errors.

Please and thanks for any help you can provide. I feel like I am VERY close here, and I have been looking for a way to extract this data for research for many weeks now.
<img width="2379" alt="screen shot 2018-04-06 at 3 29 43 pm" src="https://user-images.githubusercontent.com/37530870/38440410-5a878f48-39af-11e8-8314-13a5d95ee2b3.png">

**Comment by brianrutledge** [comment]
also, for the record, we have notified all members in this group well in advance that data would be extracted, and this data extraction is only to collect posts and comments, without any author information, from a specific timeframe.

**Comment by strohne** [comment]
I have bad news for you: "As of April 4, 2018, this node and its edges return empty data sets for GET operations unless the calling app has gone through App Review. Please see the Groups API section of the Breaking Changes changelog for more information."  See https://developers.facebook.com/docs/graph-api/changelog/breaking-changes/#groups-4-4

What you could try: register your own app, go through the review process and use the client id with Facepager. Looks like there is no way anymore.

**Comment by brianrutledge** [comment]
alright, well as it turns out the ethics review board has requested we offer the membership an additional 3 weeks to opt out prior to data extraction, so I have some time to figure out what it means to register my own app and submit it for review.

Any easy guides for that process you know of? And will I need to create an actual app (which I'd have no idea how to do), or no?

**Comment by strohne** [comment]
You need to create an app on Facebook, but this is easy. This only means you have to register a name for the app and define some settings. See https://github.com/strohne/Facepager/blob/master/src/credentials.py.readme

I have no experience with the review process. It would be really helpful if you tried this out and let me know how it worked out.

**Comment by brianrutledge** [comment]
So. I just created my own app and went through all the steps to submit that new app for the review process. Whooooo boy, this is now a super involved task. They want written explanations and full screencast video demonstrating functionality. (which, if I had, I would not even being looking got  they're help anyway.

Anyway, I did as you suggested. I read the credentials document and filled myself out all the required info and saved it as a .py file. Now I've run face pager, log-in using my FB login, and then I entered the APP ID where face pager says Client ID. I'm using an temporary user access token granted to me for the sake of this app.... Well, none of that seemed to help, since now suddenly  each time I set some parameters in facepger and then clink on "Fetch Data' it kicks back a constant "no connection to database".

WHAT TO DO!

**Comment by strohne** [comment]
Great you tried it out. Maybe we can use your screencasts as tutorials later on ;)

Some hints:
- You don't need to create a .py file.  I just directed you to this file to give you some hints about the settings of your Facebook app (on Facebook). You only need the Client ID of your app.
- Enter the client id into the field of Facepager _before_ logging in.
- "No connections to database" means you didn't create a database...click "New Database"

If this doesn't help please give some more info about your settings in Facepager (e.g. a Screenshot).

**Comment by votuduc** [comment]
@brianrutledge  @strohne  

How everything is going?

I tried to put my Facebook App ID into Client ID of Facepager.
I then put the App Token of my Facebook APP ID into Access Token of Facepager.

After hiting login to Facebook, I get a pop-ups with messages as below: 

> You are not logged in: You are not logged in. Please log in and try again. 

How to do? Please help.

**Comment by strohne** [comment]
Sorry, I don't understand yet. What you have to do: put your App-ID into the field `Client Id`. Then click `Login to Facebook`. A login window pops up, there you should see the name of your App. By logging in an access token is fetched and automatically put into the corresponding field.

**Comment by strohne** [comment]
I close this since it is no problem related to the development of Facepager, but to the usage of Facepager.

**Comment by brianrutledge** [comment]
I understand the closure. In the end the new FB review process was more
cumbersome and time intensive than my project timeline could accomodate. We
ended up just using Grytics.

**Comment by strohne** [comment]
Anyway, glad you tried it out.
