### ISSUE TITLE
Not receiving the reactions/comments/shares from FB page posts

### ISSUE THREAD

**Issue by domas36** [strohne/Facepager#87]
Hello, I'm trying to get a list of a FB page with the number of reactions, comments and shares. The first  step works well – I get the posts with their text and post id. But when I try to receive the data about those posts, I get empty columns. Tried doing it manually or using the presents as well. Could you help me please? Or has Facebook stopped providing this info?

![image](https://user-images.githubusercontent.com/38493772/38926117-4522afd4-430a-11e8-8bce-b9ec3f0664e7.png)

**Comment by strohne** [comment]
I added a preset, check it out. Just for you :)

**Comment by strohne** [comment]
And check the details of your data, maybe the keys of the columns are different. And finally: please ask further question about using Facepager in the Facebook group, not here.
