### ISSUE TITLE
error 400

### ISSUE THREAD

**Issue by SSSBiney** [strohne/Facepager#88]
Dear all, 
when i try to fetch the data from the object_id it work, But for only that single object_id. However, when I am try to fetch data from the friends of object_id it get error, why? pleaes help

**Comment by strohne** [comment]
This is no Facepager development issue but about using the Facebook API. Please ask your question in the Facebook group: https://www.facebook.com/groups/facepagerusers

And please be more precise about your settings and what you tried.
