### ISSUE TITLE
Cannot authenticate with Google using 2 factor authentication via android

### ISSUE THREAD

**Issue by ds10** [strohne/Facepager#89]
Issue: I am using 2 factor authentication with my Google Account. When trying to log in to Google on the Facepager youtube module, The log in screen asks me to confirm by pressing a confirmation screen that appears seperatly on my android device. After confirming on my android device nothing happens.

Expected behaviour: After pressing confirm on my android device, the login box should close and I should be logged in. 

Actual behaviour: Log in box will not close and I can not log in.

Context: Windows 10, facepager 3.9, 2 factor authetication set up with android phone

Current Workaround: Turning 2 factor authentication off in my google account

**Comment by strohne** [comment]
thanks for the decent error report. I hope to dig into this in the next weeks.

**Comment by strohne** [comment]
Another workaround: use SMS as second factor.

**Comment by meriem-k** [comment]
Hello, I installed facpager 4.0 once I login facebook or google it outputs an error msg: Faild create opengl 2.0 .
of solutions tks

**Comment by strohne** [comment]
This is an old issue without updates. I guess it works by now, and I close the issue.
