### ISSUE TITLE
issue in exporting all data

### ISSUE THREAD

**Issue by world33** [strohne/Facepager#91]
I have an issue in exporting all data.
I use the Youtube channel information preset; I add the node UC_1bnT3_ELtqWMnTHh82Ljw (Youtube ID) and I want to extract the youtube username hongkongbaptistu (which is shown under snippet.customUrl). Facepager extracts all fields successfully but when I export the data it does not show any data past snippet.description. status.privacyStatus and all following fields are blank in the exported csv file. Am I doing something wrong or is it a bug?
A Facepager screenshot is available at https://www.facebook.com/photo.php?fbid=10155456760112167&set=gm.271532103464656&type=3&theater&ifg=1

**Comment by strohne** [comment]
Works for me. Could you be more precise with your settings and maybe provide an example csv file with the missing fields?

**Comment by strohne** [comment]
This is an excel issue. Open excel with a blank file, then use the text import wizard (data ribbon, load from text). I close the issue.
