### ISSUE TITLE
Problem with fetching shared events 

### ISSUE THREAD

**Issue by meinungsfuehrer** [strohne/Facepager#93]
Hey,
thx for the awesome programme! 
There seems to be a problem with fetching shared events on a Facebook Feed. Have I missed a parameter to include into "fields" or are shared events excluded from fetching Feeds or Posts? 

One example: 
https://www.facebook.com/pg/JusosNordhessen/posts/ shared an event on 2nd of October containing the messsage "Hallo ihr alle [...]". I tried both <Object ID>/posts and <Object ID>/feed but these shared events don´t get fetched with the following fields:
picture,from,object_id,privacy,events,actions,updated_time,application,link,permalink_url,shares,created_time,message,icon,type,id,status_type,comments.limit(1).summary(true),likes.limit(1).summary(true),reactions.type(LIKE).limit(0).summary(1).as(like),
reactions.type(LOVE).limit(0).summary(1).as(love),
reactions.type(HAHA).limit(0).summary(1).as(haha),
reactions.type(WOW).limit(0).summary(1).as(wow),
reactions.type(SAD).limit(0).summary(1).as(sad),
reactions.type(ANGRY).limit(0).summary(1).as(angry)

I would be pleased if you could help me!

**Comment by strohne** [comment]
The general access to data does not depend on the fields setting. Events need special permissions, see https://developers.facebook.com/docs/graph-api/reference/event/

BTW: please ask questions about using Facepager or about specific APIs in the Facebook Group, not on GitHub. GitHub issues should only be used for development issues.
